### PR TITLE
ignition-common3 3.8.0

### PR DESCRIPTION
**Pull request by osrfbuild**

### CODE REVIEW

**Comment by chapulina** [comment]
build bottle

But note that `brew style` is complaining

**Comment by scpeters** [comment]
> But note that `brew style` is complaining

fix in #1231

**Comment by scpeters** [comment]
build bottle

**Comment by scpeters** [comment]
oh I guess it didn't need another build

**Comment by scpeters** [comment]
I cancelled the 2nd build and will merge as is

**Pull request merged**
