### PR TITLE
Garden: revisions bump for #2587

### PR DESCRIPTION
**Pull request by j-rivero**

### CODE REVIEW

**Comment by j-rivero** [comment]
build bottle

**Comment by scpeters** [comment]
part of https://github.com/osrf/homebrew-simulation/issues/2587

**Comment by scpeters** [comment]
only the gz-msgs10 build succeeded, investigating...

**Comment by scpeters** [comment]
it looks like this is a mix of different collections:

* gz-msgs10 is from harmonic
* the rest are from garden

in https://github.com/osrf/homebrew-simulation/pull/2574, I used the following command to generate the revision bumps for a subset of dependencies of `gz-garden.rb`, with the subset determined using a regular expression to match formula names starting with `gz-` or `sdf`:

~~~
cd $(brew --prefix osrf/simulation)/Formula
for f in $(grep -L '^ *bottle do' $(grep -rnI 'depend.*"[gs][zd][-f]' gz-garden.rb | sed -e 's@.* "@@' -e 's@"@.rb@'))
do
    brew bump-revision --message="rebuild bottle" $f
done
~~~

**Pull request merged**
