### PR TITLE
ignition-gazebo4 4.7.0

### PR DESCRIPTION
**Pull request by osrfbuild**

### CODE REVIEW

**Comment by chapulina** [comment]
build bottle

**Comment by scpeters** [comment]
the sdformat10 was uploaded with an incorrect filename due to a bug that was recently fixed by https://github.com/Homebrew/brew/pull/11097. I manually renamed the sdformat10 bottles on s3, and will try this build again

build bottle

**Comment by scpeters** [comment]
the uploaded filename is still wrong. I've commented at https://github.com/Homebrew/brew/pull/11092/files#r611096710 and will open an issue if necessary.

let's hold off on merging this for now

**Comment by scpeters** [comment]
ok, I think the file names are now fixed by https://github.com/Homebrew/brew/pull/11106

let's try again

build bottle

**Comment by scpeters** [comment]
I manually confirmed that bottle uploads are fixed

**Pull request merged**
