### PR TITLE
sdformat8: remove boost dependency

### PR DESCRIPTION
**Pull request by scpeters**

### CODE REVIEW

**Comment by scpeters** [comment]
this bottle doesn't build with xcode9

**Comment by nkoenig** [comment]
@scpeters is this a case of requiring a newer version of macos and xcode?

**Comment by scpeters** [comment]
the bottle build complains that it can't find `<any>`

* https://build.osrfoundation.org/view/os_homebrew/job/generic-release-homebrew_bottle_builder-highsierra/180/console

I just checked, and high sierra does have `<experimental/any>`, but it doesn't have `<experimental/variant>`, which is also required for the new sdformat. So, I think this won't work until mojave

**Comment by nkoenig** [comment]
Thanks, and it looks like mojave will be released in september/october of 2018.

**Comment by scpeters** [comment]
see #496

**Pull request closed without merging**
