### PR TITLE
gz-harmonic 1.0.0~pre2

### PR DESCRIPTION
**Pull request by osrfbuild**

### CODE REVIEW

**Comment by j-rivero** [comment]
build bottle

**Comment by scpeters** [comment]
build failed due to a merge that happened after build had started (see https://github.com/osrf/homebrew-simulation/issues/1990). I'll restart it after merging a couple other ones

**Comment by scpeters** [comment]
build bottle

**Comment by scpeters** [comment]
wait until https://github.com/osrf/homebrew-simulation/pull/2375 has finished building before merging this

**Pull request merged**
