### PR TITLE
ign-rendering4 update

### PR DESCRIPTION
**Pull request by iche033**

### CODE REVIEW

**Comment by iche033** [comment]
@scpeters the mojave bottle builds have been failing so I triggered rebuild a few times but no luck. The latest highsierra bottle also failed :( 

These lines look suspicious but not sure if it's the cause of the failure

```
==> brew cleanup --prune=3
Error: undefined method `disabled?' for #
```
do you know how to resolve this issue?

**Comment by scpeters** [comment]
this issue is caused by a lack of synchronization between the brew and homebrew-test-bot repositories. the following changes need to be merged in sync, but our scripts use the master branch of homebrew-test-bot but sometimes seem to use the latest tag of brew, which doesn't yet include the brew PR

* https://github.com/Homebrew/homebrew-test-bot/pull/350
* https://github.com/Homebrew/brew/pull/7190

options:

* make bottle build jobs to always use brew master
* make a custom branch of homebrew-test-bot on a fork and pass that in build parameters

I'll work on the 2nd option

**Comment by scpeters** [comment]
there are actually 3 problems in some of the mojave builds

* the afore-mentioned `undefined method `disabled?'` bug that can be fixed with a new branch of test-bot
* the Xcode version was out of date on sentinel, causing a `brew doctor` error (I upgraded it on sentinel this morning, but I think glados still needs to be updated)
* there was a bug with the pkg-config file for curl, needed by ignition-fuel-tools caused by a recent change to homebrew, but I think that has been reverted (see https://github.com/osrf/homebrew-simulation/pull/995#issuecomment-610276166)

**Comment by scpeters** [comment]
here's a build with a branch from my fork

* [Build Status](https://build.osrfoundation.org/job/generic-release-homebrew_bottle_builder/742/) https://build.osrfoundation.org/job/generic-release-homebrew_bottle_builder/742/
* https://github.com/scpeters/homebrew-test-bot/tree/before_disabled_api

**Comment by iche033** [comment]
thanks for looking into this! 

the latest build failed with the same error :(

**Comment by scpeters** [comment]
yeah, trying to change the branch didn't work because it was a rewind and the release-tools script does `git pull`. I need to add an actual commit that reverts the undesired behavior...

**Comment by scpeters** [comment]
https://github.com/scpeters/homebrew-test-bot/commit/20ae8a0ac164793e84a8478061805252d986a00e

[Build Status](https://build.osrfoundation.org/job/generic-release-homebrew_bottle_builder/743/) https://build.osrfoundation.org/job/generic-release-homebrew_bottle_builder/743/

**Comment by scpeters** [comment]
ok, now it's just down the pkg-config bug

**Comment by scpeters** [comment]
I reported it as an issue and think I have a fix

* https://bitbucket.org/ignitionrobotics/ign-cmake/issues/72/private-dependencies-of-core-library
* https://bitbucket.org/ignitionrobotics/ign-cmake/branch/pkgconfig_requires_private?dest=ign-cmake2#commits

**Comment by scpeters** [comment]
I disabled the ignition-gazebo4 pkg-config test in https://github.com/osrf/homebrew-simulation/commit/8d0ba9d9f99cf5dc2a7493b2c8868c2d26d1e7d6

**Comment by scpeters** [comment]
[Build Status](https://build.osrfoundation.org/job/generic-release-homebrew_bottle_builder/745/) https://build.osrfoundation.org/job/generic-release-homebrew_bottle_builder/745/

**Comment by iche033** [comment]
:tada: 

thanks!

**Pull request merged**
