### PR TITLE
sdformat8: update commit

### PR DESCRIPTION
**Pull request by chapulina**
Bump to [this commit](https://bitbucket.org/osrf/sdformat/commits/019a5ed58841790bb34304c8c95395e6667745bb?at=sdf8) for [this ign-gazebo PR](https://bitbucket.org/ignitionrobotics/ign-gazebo/pull-requests/251/acropolis-more-ign-msgs-sdf-conversions/diff).

### CODE REVIEW

**Comment by scpeters** [comment]
I'd prefer to point to the commit from the pull request that bumps the version number:

* https://bitbucket.org/osrf/sdformat/pull-requests/516/810-pre1/diff

we also need to specify the version explicitly `8.1.0~pre1~1~20190409~cfd1f1e63`

once that is updated, we can start a bottle build

**Comment by chapulina** [comment]
Thanks, @scpeters , see 197f2d0

**Comment by scpeters** [comment]
Ok, this looks good. Do you want me to show you how to start a bottle build?

here are example parameters for #658

* https://build.osrfoundation.org/view/os_homebrew/job/generic-release-homebrew_bottle_builder/233/parameters/

only the pull request URL is really needed; the other fields are just used for the commit message

**Comment by chapulina** [comment]
:bomb:  :boom: [Build Status](https://build.osrfoundation.org/view/os_homebrew/job/generic-release-homebrew_bottle_builder/252/)

**Comment by scpeters** [comment]
:tada: it passed!

**Pull request merged**
