### PR TITLE
ignition-launch5 5.1.0

### PR DESCRIPTION
**Pull request by osrfbuild**

### CODE REVIEW

**Comment by adityapande-1995** [comment]
build bottle

**Comment by scpeters** [comment]
there was an error message in the console log about rpath, so I've fixed that in https://github.com/osrf/homebrew-simulation/pull/1835/commits/3eec89010387bed734800b20d47feda097a62317 and will build again

build bottle

**Comment by scpeters** [comment]
build bottle

**Comment by adityapande-1995** [comment]
Checks passed !

**Pull request merged**
