### PR TITLE
gz-cmake4 4.0.0

### PR DESCRIPTION
**Pull request by osrfbuild**

### CODE REVIEW

**Comment by azeey** [comment]
I plan to wait for all Ionic releases and built them all together.

**Comment by scpeters** [comment]
> I plan to wait for all Ionic releases and built them all together.

I would wait to build gz-msgs and dependents until the next protobuf update lands (see https://github.com/osrf/homebrew-simulation/issues/2791)

* https://github.com/Homebrew/homebrew-core/pull/191155

**Comment by scpeters** [comment]
> > I plan to wait for all Ionic releases and built them all together.
> 
> I would wait to build gz-msgs and dependents until the next protobuf update lands (see #2791)
> 
> * [protobuf 28.2 Homebrew/homebrew-core#191155](https://github.com/Homebrew/homebrew-core/pull/191155)
> 
> I think it's close

it has been merged, so feel free to proceed when ready

**Comment by azeey** [comment]
See #2827

**Pull request closed without merging**
