### PR TITLE
ignition-sensors4 and ignition-rendering4: new formulas

### PR DESCRIPTION
**Pull request by iche033**

### CODE REVIEW

**Comment by scpeters** [comment]
to start a bottle builder job, start the following jenkins job with the URL of this pull request:

* https://build.osrfoundation.org/job/generic-release-homebrew_bottle_builder

the other fields are used in the commit message, so they are nice-to-have but optional

**Comment by iche033** [comment]
started bottle builder job:

https://build.osrfoundation.org/job/generic-release-homebrew_bottle_builder/660/

**Comment by scpeters** [comment]
there was an issue with the jenkins scripts that prevented the bottle from being updated, but I've fixed it in the following PR:

* https://bitbucket.org/osrf/release-tools/pull-requests/955/use-git-checkout-track-pr_head-branch-to/diff

**Comment by scpeters** [comment]
the azure pipelines CI checks are now broken (see #969), so we should just merge this. once we switch to GitHub actions, we should again have confirmation that the bottles were uploaded correctly

**Pull request merged**
