### PR TITLE
gz-sensors8 8.1.0

### PR DESCRIPTION
**Pull request by osrfbuild**

### CODE REVIEW

**Comment by iche033** [comment]
build bottle

**Comment by scpeters** [comment]
many dependencies are unbottled due to https://github.com/osrf/homebrew-simulation/issues/2651

I'll revision bump the dependencies of gz-sensors8 in this PR

**Comment by scpeters** [comment]
> I'll revision bump the dependencies of gz-sensors8 in this PR

done with a script from #2610 

~~~
for f in $(.github/ci/unbottled_dependencies.sh gz-sensors8)
do
    brew bump-revision  --message="rebuild for gdal" $f
done
~~~

**Comment by scpeters** [comment]
build bottle

**Pull request merged**
