### PR TITLE
ign-cmake1: latest commit

### PR DESCRIPTION
**Pull request by chapulina**

### CODE REVIEW

**Comment by chapulina** [comment]
@j-rivero does this look good to you? I'm hoping to fix https://github.com/osrf/homebrew-simulation/pull/457

**Comment by j-rivero** [comment]
> @j-rivero does this look good to you? I'm hoping to fix #457

Looks good to me.

**Comment by scpeters** [comment]
well done

**Comment by chapulina** [comment]
Thanks, but it didn't solve the problem :cry:

**Pull request merged**
