### PR TITLE
New snapshot of ignition-common: 0.4.0-20170720-2071c29

### PR DESCRIPTION
**Pull request by j-rivero**
Generate a snapshot of ignition-common that is able to build gazebo_experimental

### CODE REVIEW

**Comment by scpeters** [comment]
I just triggered new bottle builds. Two were successful, but there is a configuration problem on the sierra machine. It's complaining about access to mercurial, but it also has an error similar to one I saw on the following build:

* https://build.osrfoundation.org/job/gazebo-ci-default-homebrew-amd64/247/console

**Comment by j-rivero** [comment]
> I just triggered new bottle builds. Two were successful, but there is a configuration problem on the sierra machine. It's complaining about access to mercurial, but it also has an error similar to one I saw on the following build:

There was a weird configuration in the sierra node in Jenkins point to /usr/local/ for the homebrew installation. I just remove it and the things seems to work fine. Let me know if you see the error again.

**Comment by scpeters** [comment]
Thanks for fixing the build machine configuration!

**Comment by scpeters** [comment]
I think there is an error in the upload script. It thinks the package name is `ign-common-` and has uploaded the bottles here:

* http://gazebosim.org/distributions/ign-common-/releases

**Comment by scpeters** [comment]
I think these are the key lines in the uploader script:

* https://bitbucket.org/osrf/release-tools/src/1ef65afd6d6/jenkins-scripts/lib/repository_uploader.bash#repository_uploader.bash-154:155

If we used an `_` instead of `-` in between date and checksum, would that work?

* `0.4.0-20170720_2071c29`

**Comment by j-rivero** [comment]
> If we used an _ instead of - in between date and checksum, would that work?

I changed it to use `~`, same that we use in our Debian packages. I'm going to launch the bottle builders again.

**Comment by scpeters** [comment]
the sierra build failed for some reason, but that caused the subsequent build to fail since mercurial was not installed. I think the following pull request may help:

* https://bitbucket.org/osrf/release-tools/pull-requests/411/try-getting-release-tools-scripts-using/diff

**Comment by j-rivero** [comment]
ready to merge, I think

**Pull request merged**
