### PR TITLE
ignition-gazebo3 3.14.0

### PR DESCRIPTION
**Pull request by osrfbuild**

### CODE REVIEW

**Comment by scpeters** [comment]
build bottle

**Comment by scpeters** [comment]
build failure reproduced:

* [Build Status](https://build.osrfoundation.org/job/ignition_gazebo-ci-ign-gazebo3-homebrew-amd64/246/) https://build.osrfoundation.org/job/ignition_gazebo-ci-ign-gazebo3-homebrew-amd64/246/

**Comment by chapulina** [comment]
This is the same issue as in

* https://github.com/gazebosim/gz-sim/pull/1663

It looks like `gpu_lidar` can't be found. I don't know enough about macOS to track down the issue. Maybe some problem building the bottle fort this?

* https://github.com/osrf/homebrew-simulation/pull/1997

**Comment by scpeters** [comment]
> This is the same issue as in
> 
> * [Fixes ign-gazebo3 homebrew build regression (#1661) gazebosim/gz-sim#1663](https://github.com/gazebosim/gz-sim/pull/1663)
> 
> It looks like `gpu_lidar` can't be found. I don't know enough about macOS to track down the issue. Maybe some problem building the bottle fort this?
> 
> * [ignition-sensors3 3.4.0 #1997](https://github.com/osrf/homebrew-simulation/pull/1997)

I think this will fix it: https://github.com/gazebosim/gz-sensors/commit/da66843e251c6ee2e82c96dd691dc2cd0cd9d32d

**Comment by scpeters** [comment]
> I think this will fix it: [gazebosim/gz-sensors@da66843](https://github.com/gazebosim/gz-sensors/commit/da66843e251c6ee2e82c96dd691dc2cd0cd9d32d)

PR in https://github.com/gazebosim/gz-sensors/pull/262

**Comment by scpeters** [comment]
> > I think this will fix it: [gazebosim/gz-sensors@da66843](https://github.com/gazebosim/gz-sensors/commit/da66843e251c6ee2e82c96dd691dc2cd0cd9d32d)
> 
> PR in [gazebosim/gz-sensors#262](https://github.com/gazebosim/gz-sensors/pull/262)

patch added in https://github.com/osrf/homebrew-simulation/pull/2008/commits/e33fe6ad4eaec052a5d2b495bfa15a23db6ebfcf

**Comment by scpeters** [comment]
build bottle

**Pull request merged**
