### PR TITLE
Ogre2.2: Bump to get bottle built

### PR DESCRIPTION
**Pull request by mjcarroll**

### CODE REVIEW

**Comment by mjcarroll** [comment]
build bottle

**Comment by scpeters** [comment]
this is failing to build

* the first failure is about sys/sysctl.h, and we should use the patch proposed in https://github.com/OGRECave/ogre-next/issues/132 (I'm not sure why that patch wasn't used; instead https://github.com/OGRECave/ogre-next/commit/5993fb634c8001a6ec8ab75a07455414f6866278 was merged without support for macOS)
* after that I see a failure to find `GL/glx.h`. adding `mesa` as a dependency fixes that
* after adding `mesa` I now see a complaint about finding `X11/extensions/Xrandr.h`

**Comment by j-rivero** [comment]
build bottle

**Comment by j-rivero** [comment]
OgreOSXGL3PlusSupport[ is failing to compile](https://build.osrfoundation.org/job/generic-release-homebrew_triggered_bottle_builder/337/label=osx_catalina/consoleFull#20972774216ea37b8d-a6d4-40ae-8431-d90c018842af) with a missing declaration of `RenderWindow`:
```
In file included from /tmp/ogre2.2-20210325-31789-7lkbar/ogre-next-3aa42f57f77a52febf0aedfc14ac83be37aafd4c/RenderSystems/GL3Plus/src/windowing/OSX/OgreGL3PlusUtil.h:32:
/tmp/ogre2.2-20210325-31789-7lkbar/ogre-next-3aa42f57f77a52febf0aedfc14ac83be37aafd4c/RenderSystems/GL3Plus/include/windowing/OSX/OgreOSXGL3PlusSupport.h:57:5: error: unknown type name 'RenderWindow'
    RenderWindow* createWindow( bool autoCreateWindow, GL3PlusRenderSystem* renderSystem, const String& windowTitle );
    ^
/tmp/ogre2.2-20210325-31789-7lkbar/ogre-next-3aa42f57f77a52febf0aedfc14ac83be37aafd4c/RenderSystems/GL3Plus/include/windowing/OSX/OgreOSXGL3PlusSupport.h:60:13: error: unknown type name 'RenderWindow'
    virtual RenderWindow* newWindow( const String &name, unsigned int width, unsigned int height, 
```
found a comment in the ogre formula about the lack of OpenGL in versions > 10. Catalina is the case. I'm unsure about this change. @scpeters , @iche033 sounds fine to you? or should we look into fixing the compilation?

**Comment by j-rivero** [comment]
build bottle

**Comment by j-rivero** [comment]
all right, mojave is happy and catalina seems able to build the bottle but ... it ended up without an `OgreMain` file :roll_eyes: 
```
t1000:lib osrf$ pwd
/usr/local/opt/ogre2.2/lib
t1000:lib osrf$ cd ..
t1000:ogre2.2 osrf$ find . -name *.dylib
./lib/OGRE-2.2/OGRE/RenderSystem_NULL.2.2.6.dylib
./lib/OGRE-2.2/OGRE/Plugin_ParticleFX.2.2.6.dylib
./lib/OGRE-2.2/OGRE/Plugin_ParticleFX.dylib
./lib/OGRE-2.2/OGRE/RenderSystem_Metal.2.2.6.dylib
./lib/OGRE-2.2/OGRE/RenderSystem_Metal.dylib
./lib/OGRE-2.2/OGRE/RenderSystem_NULL.dylib
t1000:ogre2.2 osrf$ ls bin/*
bin/OgreCmgenToCubemap	bin/OgreMeshTool
```
I've no idea why this is happening, found some references to [missing OgreMain in Mac in the ogre wiki for premake build system](http://wiki.ogre3d.org/Premake).

**Comment by scpeters** [comment]
> OgreOSXGL3PlusSupport[ is failing to compile](https://build.osrfoundation.org/job/generic-release-homebrew_triggered_bottle_builder/337/label=osx_catalina/consoleFull#20972774216ea37b8d-a6d4-40ae-8431-d90c018842af) with a missing declaration of `RenderWindow`:
> 
> ```
> In file included from /tmp/ogre2.2-20210325-31789-7lkbar/ogre-next-3aa42f57f77a52febf0aedfc14ac83be37aafd4c/RenderSystems/GL3Plus/src/windowing/OSX/OgreGL3PlusUtil.h:32:
> /tmp/ogre2.2-20210325-31789-7lkbar/ogre-next-3aa42f57f77a52febf0aedfc14ac83be37aafd4c/RenderSystems/GL3Plus/include/windowing/OSX/OgreOSXGL3PlusSupport.h:57:5: error: unknown type name 'RenderWindow'
>     RenderWindow* createWindow( bool autoCreateWindow, GL3PlusRenderSystem* renderSystem, const String& windowTitle );
>     ^
> /tmp/ogre2.2-20210325-31789-7lkbar/ogre-next-3aa42f57f77a52febf0aedfc14ac83be37aafd4c/RenderSystems/GL3Plus/include/windowing/OSX/OgreOSXGL3PlusSupport.h:60:13: error: unknown type name 'RenderWindow'
>     virtual RenderWindow* newWindow( const String &name, unsigned int width, unsigned int height, 
> ```
> 
> found a comment in the ogre formula about the lack of OpenGL in versions > 10. Catalina is the case. I'm unsure about this change [f45b408](https://github.com/osrf/homebrew-simulation/commit/f45b4081124cf57e18bec58f12684715dc45739e). @scpeters , @iche033 sounds fine to you? or should we look into fixing the compilation?

no, we shouldn't disable that yet. macOS hasn't yet removed GL

**Comment by scpeters** [comment]
let's revert f45b408 and keep trying

**Comment by mjcarroll** [comment]
It looks like there is an API change between `RenderWindow` and `Window`, which is expected from the migration guide: https://ogrecave.github.io/ogre-next/api/2.2/_ogre22_changes.html

It may be that the macOS openGL support never got updated for 2.2?

**Comment by j-rivero** [comment]
> It may be that the macOS openGL support never got updated for 2.2?

From the README in the branch v2.2:
```
(**) Metal Backend is highly recommended. GL backend is supported in macOS, but the window subsystem hasn't been ported to 2.2 yet.
```

**Comment by srmainwaring** [comment]
I'm attempting to port GL3Plus support for macOS from Ogre2.1 to Ogre2.2 with a view to getting UI support for ignition gazebo on macOS 11.4+.

There's a discussion here: [[2.2] GL3+ support for macOS](https://forums.ogre3d.org/viewtopic.php?f=25&t=96354).

And a WIP patch to the v2-2-egl branch: https://github.com/srmainwaring/ogre-next/tree/feature/v2-2-egl-macos.

Would appreciate any help / suggestions.

**Comment by scpeters** [comment]
closing in favor of #1552

**Pull request closed without merging**
