### PR TITLE
New ignition-rndf formula (take II)

### PR DESCRIPTION
**Pull request by j-rivero**
Replaces pull request #229

### CODE REVIEW

**Comment by j-rivero** [comment]
I expect the test to fail due to [this bug](https://bitbucket.org/ignitionrobotics/ign-rndf/pull-requests/3/fix-pkg-config-include-path/diff) in upstream code.

**Comment by scpeters** [comment]
I added a patch for the commit from bitbucket that fixes the test, and also fixed the test so it could compile. This looks good to me. Do you want to build bottles now or later?

**Comment by j-rivero** [comment]
> I added a patch for the commit from bitbucket that fixes the test, and also fixed the test so it could compile. This looks good to me. Do you want to build bottles now or later?

we can release a new version that adds the pkg-config commit and build from there. So +1 for merging and remove the patch afterwards.

**Comment by scpeters** [comment]
sounds good. this should allow the homebrew CI jobs to get the dependencies installed

**Pull request merged**
