### PR TITLE
gz-rendering7 7.3.1, rebuild gz-sim7

### PR DESCRIPTION
**Pull request by osrfbuild**

### CODE REVIEW

**Comment by iche033** [comment]
build bottle

**Comment by scpeters** [comment]
build bottle

**Comment by scpeters** [comment]
I've disabled the pkg-config test for gz-rendering7 in https://github.com/osrf/homebrew-simulation/pull/2237/commits/5da324c956d9d1e7a9bac791baa1629000fc3eb8 since it is failing to find the `gl.pc` file, which is required by the core library as of https://github.com/gazebosim/gz-rendering/pull/840

**Comment by scpeters** [comment]
build bottle

**Comment by scpeters** [comment]
build bottle

**Pull request merged**
