### PR TITLE
ignition-math6 6.8.0

### PR DESCRIPTION
**Pull request by osrfbuild**

### CODE REVIEW

**Comment by chapulina** [comment]
build bottle

**Comment by scpeters** [comment]
build bottle

**Comment by scpeters** [comment]
annoying jenkins timeout. I'm going to merge #1396 then restart this and maybe another one as well

**Comment by scpeters** [comment]
build bottle

**Comment by scpeters** [comment]
wait for #1400 and #1401 to finish before merging

**Pull request merged**
