### PR TITLE
ignition-citadel 1.0.0

### PR DESCRIPTION
**Pull request by osrfbuild**

### CODE REVIEW

**Comment by j-rivero** [comment]
bottles are failing in Jenkins with the error:
```
Error: No known CI provider detected! If you are using GitHub Actions, Jenkins,
Azure Pipelines, Travis CI or Circle CI then we cannot find the expected
environment variables! Check you have e.g. exported them to a Docker container
```

**Comment by j-rivero** [comment]
> bottles are failing in Jenkins with the error:

uh probably not the error that making the build to fail. There is one before:
```
==> FAILED
Error: 1 problem in 1 formula detected
osrf/simulation/ignition-citadel:
  * stable: sha256 changed without the version also changing; please create an issue upstream to rule out malicious circumstances and to find out why the file changed.
```

**Comment by scpeters** [comment]
I pushed dd54e3f1e8fbadd1c239921cd1593bf96c717c54 to master, which I think will help if we rebase this onto it

**Comment by scpeters** [comment]
I'm having trouble pushing to GitHub; @j-rivero  can you rebase this?

**Comment by j-rivero** [comment]
> I'm having trouble pushing to GitHub; @j-rivero can you rebase this?

I did it, probably not the right way since I see changes not corresponding to this PR. The build is now green and changes looks good anyway.

The bottle generation fails due to [problems with testing on Mojave](https://build.osrfoundation.org/job/generic-release-homebrew_bottle_builder/label=osx_mojave/604/console)

**Comment by j-rivero** [comment]
I somehow broke the bottle generation with this PR. Follow in #933

**Pull request closed without merging**
