### PR TITLE
ignition-cmake2 2.7.0

### PR DESCRIPTION
**Pull request by osrfbuild**

### CODE REVIEW

**Comment by chapulina** [comment]
build bottle

**Comment by j-rivero** [comment]
Umm. Seems like internal problem with the test-bot somehow. Any pointer @scpeters ?
```
==> brew uninstall --force cmake gdbm mpdecimal openssl@1.1 pkg-config python@3.9 readline sphinx-doc sqlite xz
Error: uninitialized constant Homebrew::Tests::Formulae::HOMEBREW_BOTTLES_EXTNAME_REGEX
Did you mean?  HOMEBREW_TAP_DIR_REGEX
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/lib/tests/formulae.rb:441:in `block in bottle_reinstall_formula'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/lib/tests/formulae.rb:441:in `bottle_reinstall_formula'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/lib/tests/formulae.rb:654:in `formula!'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/lib/tests/formulae.rb:20:in `block in run!'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/lib/tests/formulae.rb:19:in `each'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/lib/tests/formulae.rb:19:in `run!'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/lib/test_runner.rb:119:in `run_tests'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/lib/test_runner.rb:36:in `block in run!'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/lib/test_runner.rb:25:in `each'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/lib/test_runner.rb:25:in `run!'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/lib/test_bot.rb:130:in `run!'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/cmd/test-bot.rb:77:in `test_bot'
/usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'
Build step 'Execute shell' marked build as failure
[Clang (LLVM based)] Skipping execution of recorder since overall result is 'FAILURE'
```

**Comment by scpeters** [comment]
> Umm. Seems like internal problem with the test-bot somehow. Any pointer @scpeters ?
> 
> ```
> ==> brew uninstall --force cmake gdbm mpdecimal openssl@1.1 pkg-config python@3.9 readline sphinx-doc sqlite xz
> Error: uninitialized constant Homebrew::Tests::Formulae::HOMEBREW_BOTTLES_EXTNAME_REGEX
> Did you mean?  HOMEBREW_TAP_DIR_REGEX
> /usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/lib/tests/formulae.rb:441:in `block in bottle_reinstall_formula'
> /usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/lib/tests/formulae.rb:441:in `bottle_reinstall_formula'
> /usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/lib/tests/formulae.rb:654:in `formula!'
> /usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/lib/tests/formulae.rb:20:in `block in run!'
> /usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/lib/tests/formulae.rb:19:in `each'
> /usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/lib/tests/formulae.rb:19:in `run!'
> /usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/lib/test_runner.rb:119:in `run_tests'
> /usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/lib/test_runner.rb:36:in `block in run!'
> /usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/lib/test_runner.rb:25:in `each'
> /usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/lib/test_runner.rb:25:in `run!'
> /usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/lib/test_bot.rb:130:in `run!'
> /usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/cmd/test-bot.rb:77:in `test_bot'
> /usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'
> Build step 'Execute shell' marked build as failure
> [Clang (LLVM based)] Skipping execution of recorder since overall result is 'FAILURE'
> ```
> 
> Seems a constant used by test-bot in master branch:
> 
> ```
> homebrew-test-bot on  master ❯ grep -R HOMEBREW_BOTTLES_EXTNAME_REGEX *
> lib/tests/formulae.rb:                     .gsub(%r{.*(\./\S+#{HOMEBREW_BOTTLES_EXTNAME_REGEX}).*}om, '\1')
> ```
> 
> Changed here [Homebrew/homebrew-test-bot#589](https://github.com/Homebrew/homebrew-test-bot/pull/589), should be in sync with change in brew core. It might be the caes that we are using `HOMEBREW_NO_AUTO_UPDATE` and it is avoiding to update brew itself so we don't get changes in the API?

I'll take a look

**Comment by scpeters** [comment]
> > Umm. Seems like internal problem with the test-bot somehow. Any pointer @scpeters ?
> > ```
> > ==> brew uninstall --force cmake gdbm mpdecimal openssl@1.1 pkg-config python@3.9 readline sphinx-doc sqlite xz
> > Error: uninitialized constant Homebrew::Tests::Formulae::HOMEBREW_BOTTLES_EXTNAME_REGEX
> > Did you mean?  HOMEBREW_TAP_DIR_REGEX
> > /usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/lib/tests/formulae.rb:441:in `block in bottle_reinstall_formula'
> > /usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/lib/tests/formulae.rb:441:in `bottle_reinstall_formula'
> > /usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/lib/tests/formulae.rb:654:in `formula!'
> > /usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/lib/tests/formulae.rb:20:in `block in run!'
> > /usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/lib/tests/formulae.rb:19:in `each'
> > /usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/lib/tests/formulae.rb:19:in `run!'
> > /usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/lib/test_runner.rb:119:in `run_tests'
> > /usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/lib/test_runner.rb:36:in `block in run!'
> > /usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/lib/test_runner.rb:25:in `each'
> > /usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/lib/test_runner.rb:25:in `run!'
> > /usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/lib/test_bot.rb:130:in `run!'
> > /usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/cmd/test-bot.rb:77:in `test_bot'
> > /usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'
> > Build step 'Execute shell' marked build as failure
> > [Clang (LLVM based)] Skipping execution of recorder since overall result is 'FAILURE'
> > ```
> > 
> > 
> > Seems a constant used by test-bot in master branch:
> > ```
> > homebrew-test-bot on  master ❯ grep -R HOMEBREW_BOTTLES_EXTNAME_REGEX *
> > lib/tests/formulae.rb:                     .gsub(%r{.*(\./\S+#{HOMEBREW_BOTTLES_EXTNAME_REGEX}).*}om, '\1')
> > ```
> > 
> > 
> > Changed here [Homebrew/homebrew-test-bot#589](https://github.com/Homebrew/homebrew-test-bot/pull/589), should be in sync with change in brew core. It might be the caes that we are using `HOMEBREW_NO_AUTO_UPDATE` and it is avoiding to update brew itself so we don't get changes in the API?
> 
> I'll take a look

seems connected to https://github.com/Homebrew/brew/pull/10948

**Comment by scpeters** [comment]
yeah, I think you're right that `HOMEBREW_NO_AUTO_UPDATE` is connected

**Comment by j-rivero** [comment]
build bottle

**Comment by j-rivero** [comment]
good to go

**Pull request merged**
