### PR TITLE
Fuel tools use common1

### PR DESCRIPTION
**Pull request by chapulina**

### CODE REVIEW

**Comment by scpeters** [comment]
This will fix our CI for the latest fuel-tools code, but it will break this formula, since the url still refers to the 0.1.3 release. Can you change the url to a bitbucket commit url from the relevant pull request (similar to #301)?

We can also run the bottle builder jobs once it there is a working url.

**Comment by chapulina** [comment]
Done, @scpeters

**Comment by scpeters** [comment]
I forgot to say we should add a version tag as well when using a bitbucket commit; so I added one in fbc52d825c9a1bd82e2761b32a32c4f85bcfd643

**Comment by scpeters** [comment]
At this point, we can rebuild the bottles. Do you want to try starting one? Just paste the URL of this pull request into the following job:

* https://build.osrfoundation.org/view/os_homebrew/job/generic-release-homebrew_bottle_builder-highsierra/build?delay=0sec

**Comment by scpeters** [comment]
@chapulina let me know if you want to try building bottles; otherwise I can do it

**Comment by chapulina** [comment]
It's building! Fingers crossed!

https://build.osrfoundation.org/view/os_homebrew/job/generic-release-homebrew_bottle_builder-highsierra/110/

**Comment by scpeters** [comment]
it worked! I'll trigger the other two bottles as well:

* https://build.osrfoundation.org/job/generic-release-homebrew_bottle_builder-sierra/build?delay=0sec
* https://build.osrfoundation.org/job/generic-release-homebrew_bottle_builder-elcapitan/build?delay=0sec

**Pull request merged**
