### PR TITLE
sdformat11 11.0.0~pre2

### PR DESCRIPTION
**Pull request by osrfbuild**

### CODE REVIEW

**Comment by chapulina** [comment]
build bottle

**Comment by scpeters** [comment]
fix for sdformat bottle in https://github.com/osrf/sdformat/pull/489

I'll add a patch here

**Comment by scpeters** [comment]
build bottle

**Comment by scpeters** [comment]
build bottle

**Comment by scpeters** [comment]
build bottle

**Review by ahcorde — APPROVED** [review]

**Pull request merged**
