### PR TITLE
ignition-rendering4: update

### PR DESCRIPTION
**Pull request by JShep1**

### CODE REVIEW

**Comment by chapulina** [comment]
@scpeters , any advice on how to handle the `Run brew test-bot` failure?

**Comment by scpeters** [comment]
did you start a bottle builder job?

**Comment by scpeters** [comment]
I added a link to the bottle builder job in the readme

**Comment by chapulina** [comment]
Ok, started one here: [Build Status](https://build.osrfoundation.org/job/generic-release-homebrew_bottle_builder/686/)

**Comment by scpeters** [comment]
the high sierra jobs on omnidroid have been failing occasionally with the following message:

~~~
ERROR: Issue with creating launcher for agent omnidroid.highsierra. The agent has not been fully initialized yet
Building remotely on omnidroid.highsierra (osx_highsierra)FATAL: Cannot retrieve the node's workspace for hudson.matrix.MatrixProject@37bdabdf[generic-release-homebrew_bottle_builder]. Most probably the node is offline
java.io.IOException: Cannot retrieve the node's workspace for hudson.matrix.MatrixProject@37bdabdf[generic-release-homebrew_bottle_builder]. Most probably the node is offline
	at hudson.matrix.MatrixRun$MatrixRunExecution.getParentWorkspaceLease(MatrixRun.java:173)
	at hudson.matrix.MatrixRun$MatrixRunExecution.decideWorkspace(MatrixRun.java:187)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:488)
	at hudson.model.Run.execute(Run.java:1853)
	at hudson.matrix.MatrixRun.run(MatrixRun.java:153)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:427)
~~~

* https://build.osrfoundation.org/job/generic-release-homebrew_bottle_builder/label=osx_highsierra/686/console

I restart them and then they seem to run fine

* [Build Status](https://build.osrfoundation.org/job/generic-release-homebrew_bottle_builder/687/) https://build.osrfoundation.org/job/generic-release-homebrew_bottle_builder/687/

**Comment by JShep1** [comment]
I reran CI for this job and am still getting a 404 for the bottle(?).  Please let me know what I can do whenever you have a chance, I'm not too familiar with Mac builds.

**Comment by scpeters** [comment]
making this pull request is only half the job of getting a new bottle; we have to start a bottle builder job (linked in the README)

at the moment, this won't work until #982 is merged though, so let's wait on that one

**Comment by scpeters** [comment]
we've merged the tinyxml2 fixes, so I started a new bottle build job

* [Build Status](https://build.osrfoundation.org/job/generic-release-homebrew_bottle_builder/702/) https://build.osrfoundation.org/job/generic-release-homebrew_bottle_builder/702/

**Comment by chapulina** [comment]
I think this branch needs to be rebased?

**Comment by scpeters** [comment]
usually they don't need to be rebased unless there are conflicts. I rebased the other one because I wanted to separate the changes in #985  so it wouldn't try to rebuild all those bottles

**Comment by scpeters** [comment]
[Build Status](https://build.osrfoundation.org/job/generic-release-homebrew_bottle_builder/706/) https://build.osrfoundation.org/job/generic-release-homebrew_bottle_builder/706/

**Pull request merged**
