### PR TITLE
Remove broken bottles for: gui2, msgs1, sensors2, transport4, transport7. gazebo9 and gazebo10

### PR DESCRIPTION
**Pull request by j-rivero**
Protobuf bump killed the ABI in some cases, Bullet bump in some others. They should be regenerated, removing them to use brew test-bot without failures while testing code.

### CODE REVIEW

**Comment by scpeters** [comment]
it looks like the `msgs1` dependency chain is properly cleared by this list, but I see some users of sensors2 and gui2 that still have bottle blocks:

~~~
$ grep gui2 $(grep -rlI 'bottle do' Formula/ | sort)
Formula//ignition-blueprint.rb:  depends_on "ignition-gui2"
Formula//ignition-gazebo2.rb:  depends_on "ignition-gui2"
Formula//ignition-launch1.rb:  depends_on "ignition-gui2"
~~~

I would include those 3 formulae as well

**Comment by j-rivero** [comment]
> it looks like the `msgs1` dependency chain is properly cleared by this list, but I see some users of sensors2 and gui2 that still have bottle blocks:

I had the feeling that I miss some of the packages. Thanks!

**Comment by j-rivero** [comment]
lets the jazz begin

**Comment by scpeters** [comment]
👍

**Pull request merged**
