### PR TITLE
ignition-msgs3 3.1.0~pre1

### PR DESCRIPTION
**Pull request by osrfbuild**

### CODE REVIEW

**Comment by chapulina** [comment]
humm it's not clear to me why the Azure build failed

**Comment by scpeters** [comment]
azure (10.13) failed because the bottles haven't been updated

travis (10.12) failed because there are no bottles to test

**Comment by scpeters** [comment]
[Build Status](https://build.osrfoundation.org/job/generic-release-homebrew_bottle_builder/204/) https://build.osrfoundation.org/job/generic-release-homebrew_bottle_builder/204/

the bottle build failed due to an upstream homebrew issue

* but I'll test it after the fix is merged ( https://github.com/Homebrew/homebrew-test-bot/pull/244 )

**Comment by scpeters** [comment]
you have to be careful when checking CI for this repo since it doesn't check if bottles are working for 10.14, so a PR to update ign-gazebo or ign-physics can pass CI before the bottles are built

**Comment by scpeters** [comment]
you're right that it isn't clear; I haven't documented how all this works

**Comment by chapulina** [comment]
No worries, I just meant to say that I looked thorough the logs and couldn't pinpoint the problem

**Comment by scpeters** [comment]
I restarted the job, and now it passed, so it commited an updated bottle block

and azure tested that a new bottle is avaiable, and it found one

**Pull request merged**
