### PR TITLE
bump formula revisions for protobuf 3.6

### PR DESCRIPTION
**Pull request by scpeters**
build bottles when https://github.com/Homebrew/homebrew-core/pull/29239 is merged

### CODE REVIEW

**Comment by ilovezfs** [comment]
C++11 across the board for this one. Not sure if you already do that :)

**Comment by scpeters** [comment]
most of our formulae are using c++11, but I haven't ever used `needs :cxx11` or `ENV.cxx11` in our formulae

**Comment by ilovezfs** [comment]
`needs :cxx11` just sets fails_with for some old compilers (should be irrelevant for you) and `ENV.cxx11` is hack when the build system itself isn't already setting -std=c++11

So neither of those should be needed.

**Comment by ilovezfs** [comment]
https://github.com/Homebrew/homebrew-core/pull/29239 is merged.

**Comment by scpeters** [comment]
thanks for the heads up!

**Pull request merged**
