### PR TITLE
ignition-rendering4 4.8.0

### PR DESCRIPTION
**Pull request by osrfbuild**

### CODE REVIEW

**Comment by chapulina** [comment]
@scpeters, do we have any fixes underway for these errors?

```
Error: Formula gazebo2 should also have a conflict declared with gazebo10
Error: Formula gazebo3 should also have a conflict declared with gazebo10
Error: Formula gazebo4 should also have a conflict declared with gazebo10
Error: Formula gazebo5 should also have a conflict declared with gazebo10
Error: Formula gazebo6 should also have a conflict declared with gazebo10
Error: Formula gazebo8 should also have a conflict declared with gazebo10
Error: Formula gazebo2 should also have a conflict declared with gazebo11
Error: Formula gazebo3 should also have a conflict declared with gazebo11
Error: Formula gazebo4 should also have a conflict declared with gazebo11
Error: Formula gazebo5 should also have a conflict declared with gazebo11
Error: Formula gazebo6 should also have a conflict declared with gazebo11
Error: Formula gazebo8 should also have a conflict declared with gazebo11
Error: Formula gazebo2 should also have a conflict declared with gazebo9
Error: Formula gazebo3 should also have a conflict declared with gazebo9
Error: Formula gazebo4 should also have a conflict declared with gazebo9
Error: Formula gazebo5 should also have a conflict declared with gazebo9
Error: Formula gazebo6 should also have a conflict declared with gazebo9
Error: Formula gazebo8 should also have a conflict declared with gazebo9
Error: Formula ignition-math2 should also have a conflict declared with ignition-math4
Error: Formula ignition-math2 should also have a conflict declared with ignition-math5
Error: Formula ignition-math2 should also have a conflict declared with ignition-math6
Error: Formula sdformat should also have a conflict declared with sdformat6
Error: Formula sdformat3 should also have a conflict declared with sdformat6
Error: Formula sdformat should also have a conflict declared with sdformat7
Error: Formula sdformat3 should also have a conflict declared with sdformat7
```

**Comment by chapulina** [comment]
Ticketed #1518

**Comment by scpeters** [comment]
> Ticketed #1518

see https://github.com/osrf/homebrew-simulation/pull/1519

**Comment by scpeters** [comment]
build bottle

**Pull request merged**
