### PR TITLE
Edifice: depend on ignition-common4

### PR DESCRIPTION
**Pull request by chapulina**
Addresses https://github.com/ignition-tooling/release-tools/issues/361

### CODE REVIEW

**Comment by chapulina** [comment]
build bottle

**Comment by chapulina** [comment]
build bottle

**Comment by scpeters** [comment]
build bottle

**Comment by scpeters** [comment]
build bottle

**Comment by scpeters** [comment]
build bottle

**Comment by scpeters** [comment]
build bottle

**Comment by scpeters** [comment]
I'll resolve the conflicts here

**Comment by scpeters** [comment]
build bottle

**Review by mjcarroll — APPROVED** [review]

**Comment by scpeters** [comment]
build bottle

**Comment by scpeters** [comment]
build bottle

**Pull request merged**
