### PR TITLE
sdformat9, gazebo11: use tinyxml1

### PR DESCRIPTION
**Pull request by scpeters**
Part of https://github.com/osrf/homebrew-simulation/issues/2503 and #2505. Depend on a `brew extract`ed formula instead of `homebrew/core/tinyxml` in preparation for the removal of `tinyxml` from homebrew-core.

### CODE REVIEW

**Comment by scpeters** [comment]
build bottle

**Comment by okalachev** [comment]
I guess, after this change I started to periodically get an error when installing gazebo11:

```
Error: Cannot install osrf/simulation/tinyxml1 because conflicting formulae are installed.
==> Installing osrf/simulation/gazebo11 dependency: osrf/simulation/tinyxml1
  tinyxml: because differing version of the same formula
```

See the log: https://github.com/okalachev/flix/actions/runs/7514522280/job/20457487348#step:3:661.

**Comment by okalachev** [comment]
@scpeters

**Comment by scpeters** [comment]
what happens if you `brew remove tinyxml`? There are only a few formulae left that use `tinyxml`, so in most cases it should be possible to remove `tinyxml` in favor of `tinyxml1`

**Comment by okalachev** [comment]
@scpeters, `tinyxml` is not installed.

It gets installed during `brew install gazebo11` for some reason: https://github.com/okalachev/flix/actions/runs/7560949053/job/20588083848#step:3:8

So `brew install gazebo11` on a clean macOS doesn't work.

**Comment by okalachev** [comment]
Update, this error gone, after a added `brew update` before installed Gazebo, but now I fell into [another error](https://github.com/okalachev/flix/actions/runs/7562498294/job/20593084074#step:4:3444) with 2to3 package installation...

**Comment by okalachev** [comment]
@scpeters, it works. Though now Gazebo [installs](https://github.com/okalachev/flix/actions/runs/7564194864/job/20598766311) on a clean macOS for 1 hour 18 minutes. I'm not sure if it's normal.

**Comment by scpeters** [comment]
> @scpeters, it works. Though now Gazebo [installs](https://github.com/okalachev/flix/actions/runs/7564194864/job/20598766311) on a clean macOS for 1 hour 18 minutes. I'm not sure if it's normal.

a new version of protobuf was recently merged to homebrew-core, which broke our binary bottles, so they are being rebuilt (see https://github.com/osrf/homebrew-simulation/issues/2527). `gz-harmonic` has been rebuilt already, and the rest should be rebuilt within a few days.

**Comment by okalachev** [comment]
@scpeters, thanks, I'll be waiting for that!

**Comment by scpeters** [comment]
the gazebo11 bottle was rebuilt in #2538

**Comment by okalachev** [comment]
@scpeters, maybe you could help?

I installed the latest version of Gazebo 11 using brew on my MacBook, but can't run it getting the error:

```
dyld[9609]: Library not loaded: /opt/homebrew/opt/jpeg-xl/lib/libjxl.0.8.dylib
  Referenced from: <7CB1CDE5-EE97-3E0F-AB68-CDCE5310A635> /opt/homebrew/Cellar/gdal/3.8.2/lib/libgdal.34.3.8.2.dylib
  Reason: tried: '/opt/homebrew/opt/jpeg-xl/lib/libjxl.0.8.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/jpeg-xl/lib/libjxl.0.8.dylib' (no such file), '/opt/homebrew/opt/jpeg-xl/lib/libjxl.0.8.dylib' (no such file), '/opt/homebrew/Cellar/jpeg-xl/0.9.1/lib/libjxl.0.8.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/jpeg-xl/0.9.1/lib/libjxl.0.8.dylib' (no such file), '/opt/homebrew/Cellar/jpeg-xl/0.9.1/lib/libjxl.0.8.dylib' (no such file)
[1]    9609 abort      gazebo
```

And the previous versions worked.

**Pull request merged**
