### PR TITLE
ignition-msgs6 6.0.0

### PR DESCRIPTION
**Pull request by osrfbuild**

### CODE REVIEW

**Comment by chapulina** [comment]
build bottle

**Comment by scpeters** [comment]
nice work; it looks good from here. when squashing and merging, I often remove the first bullet point of the commit message if it matches the title; maybe I should add that to the README

**Comment by chapulina** [comment]
> I often remove the first bullet point of the commit message if it matches the title

Do you mean I should keep all other bullets, or try to combine them into a meaningful commit message?

**Comment by scpeters** [comment]
I usually keep the `* update bottle` line: https://github.com/osrf/homebrew-simulation/commit/51416ecc575ff0ecca4641ef79b5855771918286

**Comment by chapulina** [comment]
Ouch, sorry, I'll do that next time

**Comment by scpeters** [comment]
> Ouch, sorry, I'll do that next time

it's fine!

**Pull request merged**
