### PR TITLE
 Harmonic: revisions bump for #2587

### PR DESCRIPTION
**Pull request by j-rivero**

### CODE REVIEW

**Comment by scpeters** [comment]
part of https://github.com/osrf/homebrew-simulation/issues/2587

**Comment by scpeters** [comment]
the gz-msgs9 bump should be replaced with a gz-msgs10 bump (see also https://github.com/osrf/homebrew-simulation/pull/2591#issuecomment-1998529556)

**Comment by j-rivero** [comment]
build bottle

**Comment by scpeters** [comment]
looks good for harmonic!

**Review by scpeters — APPROVED** [review]

**Pull request merged**
