### PR TITLE
Bump gazebo11 revision to fix boost symbol change

### PR DESCRIPTION
**Pull request by j-rivero**
related to #1185

### CODE REVIEW

**Comment by j-rivero** [comment]
build bottle

**Comment by scpeters** [comment]
yep, the gazebo bottle has been failing for a couple days, but I hadn't noticed:

* [Build Status](https://build.osrfoundation.org/job/gazebo-install-one_liner-homebrew-amd64/1842/) https://build.osrfoundation.org/job/gazebo-install-one_liner-homebrew-amd64/1842/

**Comment by scpeters** [comment]
looks like a compilation error; I'm looking into it

**Comment by scpeters** [comment]
boost shared_ptr has changed slightly in 1.74; I am about to submit a patch to fix it

**Comment by scpeters** [comment]
> boost shared_ptr has changed slightly in 1.74; I am about to submit a patch to fix it

patch submitted in https://github.com/osrf/gazebo/pull/2862 and added in to the gazebo11 formula in this PR

**Comment by scpeters** [comment]
build bottle

**Pull request merged**
