### PR TITLE
dartsim@6.10.0: new formula

### PR DESCRIPTION
**Pull request by j-rivero**

### CODE REVIEW

**Comment by azeey** [comment]
I believe the commit [fdde7e7894ebc36bae8811f7a63e5b1c899bb4af](https://github.com/azeey/dart/commit/fdde7e7894ebc36bae8811f7a63e5b1c899bb4af) is from https://github.com/azeey/dart/ not https://github.com/dartsim/dart

**Comment by j-rivero** [comment]
> I believe the commit [fdde7e7894ebc36bae8811f7a63e5b1c899bb4af](https://github.com/azeey/dart/commit/fdde7e7894ebc36bae8811f7a63e5b1c899bb4af) is from https://github.com/azeey/dart/ not https://github.com/dartsim/dart

Ouch good catch. Fixed.

**Comment by j-rivero** [comment]
all right I think we get it. New dart formula based on our fork of DART and the ign-physics bottle rebuilt using the new DART. I've checked that it includes the dartsim modules in ign-phyiscs. All is fine as far as I can tell.

**Comment by scpeters** [comment]
I'll be back tomorrow and haven't test this, but it looks ok from a cursory glance

**Comment by scpeters** [comment]
we might need to add a conflicts_with `dartsim` and we probably won't be able to have gazebo9/10 installed side-by-side with ignition-gazebo

instead of conflicts_with, we could make `dartsim@6.10.0` keg-only and add some helper logic to release-tools

**Comment by scpeters** [comment]
pointer to the release-tools script workaround for keg-only packages:

* https://bitbucket.org/osrf/release-tools/src/70c0103fe986782c4032bd72445cc8093dc2024c/jenkins-scripts/lib/project-default-devel-homebrew-amd64.bash#lines-109:121

**Comment by j-rivero** [comment]
> instead of conflicts_with, we could make `dartsim@6.10.0` keg-only and add some helper logic to release-tools

sounds more useful to me. I've change the formula and created a PR https://bitbucket.org/osrf/release-tools/pull-requests/852

**Comment by j-rivero** [comment]
After changing the formula to keg-only the test is failing due to problems locating libs. I tried to workaround the problem with 3786a3b but seems like it is not working. Any suggestion @scpeters ?

**Comment by scpeters** [comment]
I'll take a look at this after my next meeting

**Comment by scpeters** [comment]
I appended the octomap opt_lib path to `DYLD_FALLBACK_LIBRARY_PATH` as well in c4d2f25, and I think this may fix this PR, but I tried building ign-gazebo2 against this PR, and it is also having problems loading libraries:

~~~
39: Error while loading the library [/usr/local/lib//libignition-physics1-dartsim-plugin.1.dylib]: dlopen(/usr/local/lib//libignition-physics1-dartsim-plugin.1.dylib, 5): Library not loaded: @rpath/libdart.6.10.dylib
39:   Referenced from: /usr/local/opt/dartsim@6.10.0/lib/libdart-collision-ode.6.10.dylib
39:   Reason: image not found
39: [Err] [Physics.cc:268] Unable to load the /usr/local/lib//libignition-physics1-dartsim-plugin.1.dylib library.
~~~

https://build.osrfoundation.org/view/ign-blueprint/job/ignition_gazebo-ci-ign-gazebo2-homebrew-amd64/25/console

I think we may need to set `DYLD_FALLBACK_LIBRARY_PATH` in that release-tools PR as well

**Comment by scpeters** [comment]
I'd like to update the ignition-physics test to try to load the dartsim plugin

**Comment by scpeters** [comment]
I've updated the test in 76cc5ad, which reproduces the rpath problem in my local testing

**Comment by j-rivero** [comment]
thanks for the fixes. LGTM

**Pull request merged**
