### PR TITLE
ignition-physics2 2.1.0

### PR DESCRIPTION
**Pull request by osrfbuild**

### CODE REVIEW

**Comment by chapulina** [comment]
The failure says `Error: invalid option: --fast`, have you seen this @scpeters ?

**Comment by scpeters** [comment]
I see the error `Error: invalid option: --ci-pr`. They recently made a ton of changes to `brew test-bot`; I'm discussing this a bit in https://github.com/osrf/homebrew-simulation/issues/1005#issuecomment-626047465

**Comment by scpeters** [comment]
I see that error in: https://build.osrfoundation.org/job/generic-release-homebrew_bottle_builder/769/label=osx_highsierra/console

**Comment by scpeters** [comment]
this bottle failed to build, and I rebuilt them due to https://github.com/osrf/homebrew-simulation/issues/1005, so I had to rebase this branch

I'll start another bottle build

**Comment by scpeters** [comment]
[Build Status](https://build.osrfoundation.org/job/generic-release-homebrew_bottle_builder/772/) https://build.osrfoundation.org/job/generic-release-homebrew_bottle_builder/772/

**Pull request merged**
