### PR TITLE
ogre1.9, ogre2.1: use libx11 instead of :x11

### PR DESCRIPTION
**Pull request by scpeters**
Attempting a fix for #1227.

### CODE REVIEW

**Comment by scpeters** [comment]
build bottle

**Comment by scpeters** [comment]
build bottle

**Comment by scpeters** [comment]
build bottle

**Comment by chapulina** [comment]
The test bot is passing, but the bottle is failing to build with:

```
[Err] [OgreRenderEngine.cc:501] unable to find OpenGL rendering system. OGRE is probably installed incorrectly. Double check the OGRE cmake output, and make sure OpenGL is enabled.
```

**Comment by scpeters** [comment]
build bottle

**Comment by scpeters** [comment]
> The test bot is passing, but the bottle is failing to build with:
> 
> ```
> [Err] [OgreRenderEngine.cc:501] unable to find OpenGL rendering system. OGRE is probably installed incorrectly. Double check the OGRE cmake output, and make sure OpenGL is enabled.
> ```

I tested locally and confirmed that `ignition-rendering*` require a rebuild as well, but should work once they are rebuilt

**Comment by scpeters** [comment]
ok, let's try it

**Pull request merged**
