### PR TITLE
Ogre 1.9

### PR DESCRIPTION
**Pull request by iche033**
extended the work done in pull request #24. Simplified to one version that grabs a specific commit from the ogre-1.9 branch.

I had to make a few other patches on top in order to get it to compile. 

In addition, I made an `ogre-1.9-cocoa_window_scale.patch` that has some backport changes to OgreCocoaWindow so that Qt5 + Ogre would work on retina displays.

### CODE REVIEW

**Comment by scpeters** [comment]
I rebased this branch and squashed some of @iche033's commits. I also fixed the `brew style` and `brew audit` complaints. I'll test the actual formula shortly.

**Comment by scpeters** [comment]
@iche033 can you add some comments next to the patches that you added?

**Comment by scpeters** [comment]
There is a linking error on my laptop running yosemite:

* https://gist.github.com/b1f9c3d9579fdb150593f567048e1d9d
* https://gist.github.com/anonymous/b1f9c3d9579fdb150593f567048e1d9d#file-02-make-L406

**Comment by scpeters** [comment]
Also, I'm using boost 1.62.0. Which boost version have you tested with?

**Comment by iche033** [comment]
added comments in b87ca0a

weird I'm on yosemite and also using boost 1.62. I just retried removing and installing again and it worked. 

I have an older xcode version: 5.1.1, not sure if that's the problem.

**Comment by iche033** [comment]
I updated xcode to 7.2.1 and was able to reproduce the linking error. I made a patch in 6efdd6a to fix it. ogre 1.9 should build now.

**Comment by scpeters** [comment]
Thanks @iche033 I'm testing it with gazebo

Also, cc @wjwwood this is ready for testing

**Comment by scpeters** [comment]
@iche033 I'm now seeing some gazebo rendering test seg-faults on homebrew when using this ogre1.9 formula. I noticed it on the [qt5_ian_context build](http://build.osrfoundation.org/job/gazebo-ci-pr_any-homebrew-amd64/825), but I can reproduce it on `gazebo7` with ogre1.9.

The tests appear to seg-fault during tear-down. Here's the console output from jenkins:

~~~
119: [ RUN      ] InertiaVisual_TEST.InertiaVisualTest
119: UNIT_InertiaVisual_TEST(39896,0x11b7af000) malloc: *** error for object 0x1000000000000000: pointer being freed was not allocated
119: *** set a breakpoint in malloc_error_break to debug
119: [Msg] Waiting for master.
119: [Msg] Connected to gazebo master @ http://127.0.0.1:11345
119: [Msg] Publicized address: 172.23.2.252
119: [Dbg] [ServerFixture.cc:201] ServerFixture load in 0.7 seconds, timeout after 600 seconds
119: [Dbg] [ServerFixture.cc:127] ServerFixture::Unload
119: 
119/602 Test #119: UNIT_InertiaVisual_TEST ...............................***Exception: Other  7.95 sec
~~~

and from my local machine:

~~~
[ RUN      ] InertiaVisual_TEST.InertiaVisualTest
[Msg] Waiting for master.
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 192.168.1.70
[Dbg] [ServerFixture.cc:200] ServerFixture load in 1.6 seconds, timeout after 600 seconds
[Dbg] [ServerFixture.cc:126] ServerFixture::Unload
UNIT_InertiaVisual_TEST(8568,0x1124a1000) malloc: *** error for object 0xa000000000000000: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6 (core dumped)
~~~

and backtrace from my local machine:

~~~
(lldb) bt
* thread #1: tid = 0x0000, 0x00007fff8ee8e136 libsystem_kernel.dylib`__psynch_cvwait + 10, stop reason = signal SIGSTOP
  * frame #0: 0x00007fff8ee8e136 libsystem_kernel.dylib`__psynch_cvwait + 10
    frame #1: 0x00007fff946ab560 libsystem_pthread.dylib`_pthread_cond_wait + 693
    frame #2: 0x0000000106db8e5b libOgreMain.1.9.0.dylib`boost::condition_variable::wait(this=0x00007f8baa7391f0, m=0x00007fff597e5648) + 75 at condition_variable.hpp:77
    frame #3: 0x0000000106db70e5 libOgreMain.1.9.0.dylib`boost::thread::join_noexcept(this=0x00007f8baa736b30) + 101 at thread.cpp:316
    frame #4: 0x00000001064589be UNIT_InertiaVisual_TEST`gazebo::ServerFixture::Unload() [inlined] boost::thread::join(this=0x00007f8baa736b30) + 29 at thread.hpp:766
    frame #5: 0x00000001064589a1 UNIT_InertiaVisual_TEST`gazebo::ServerFixture::Unload(this=<unavailable>) + 225 at ServerFixture.cc:137
    frame #6: 0x000000010645201c UNIT_InertiaVisual_TEST`void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) [inlined] void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(method=<unavailable>, location=<unavailable>)(), char const*) + 156 at gtest.cc:2079
    frame #7: 0x000000010645200f UNIT_InertiaVisual_TEST`void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(object=<unavailable>, method=<unavailable>, location=<unavailable>)(), char const*) + 143 at gtest.cc:2115
    frame #8: 0x000000010643e6b2 UNIT_InertiaVisual_TEST`testing::TestInfo::Run(this=0x00007f8baa416560) + 370 at gtest.cc:2327
    frame #9: 0x000000010643eda3 UNIT_InertiaVisual_TEST`testing::TestCase::Run(this=0x00007f8baa416650) + 451 at gtest.cc:2445
    frame #10: 0x00000001064462bb UNIT_InertiaVisual_TEST`testing::internal::UnitTestImpl::RunAllTests(this=0x00007f8baa410800) + 939 at gtest.cc:4316
    frame #11: 0x00000001064526f4 UNIT_InertiaVisual_TEST`bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) [inlined] bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(method=<unavailable>, location=<unavailable>)(), char const*) + 14 at gtest.cc:2079
    frame #12: 0x00000001064526e6 UNIT_InertiaVisual_TEST`bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(object=<unavailable>, method=<unavailable>, location="auxiliary test code (environments or event listeners)")(), char const*) + 134 at gtest.cc:2115
    frame #13: 0x0000000106445ebe UNIT_InertiaVisual_TEST`testing::UnitTest::Run(this=<unavailable>) + 174 at gtest.cc:3927
    frame #14: 0x000000010642d011 UNIT_InertiaVisual_TEST`main [inlined] RUN_ALL_TESTS() + 33 at gtest.h:2288
    frame #15: 0x000000010642d004 UNIT_InertiaVisual_TEST`main(argc=<unavailable>, argv=<unavailable>) + 20 at InertiaVisual_TEST.cc:139
    frame #16: 0x00007fff8f2f95c9 libdyld.dylib`start + 1
(lldb) 
~~~

**Pull request merged**
