### PR TITLE
ignition-msgs4 blueprint bump

### PR DESCRIPTION
**Pull request by chapulina**
This commit: https://bitbucket.org/ignitionrobotics/ign-msgs/commits/b82726d01252e141847335da3e8144d4e4cba54b

Matching debian nightlies are being triggered.

### CODE REVIEW

**Comment by scpeters** [comment]
[Build Status](https://build.osrfoundation.org/job/generic-release-homebrew_bottle_builder/291/) https://build.osrfoundation.org/view/os_homebrew/job/generic-release-homebrew_bottle_builder/291/

**Comment by scpeters** [comment]
[Build Status](https://build.osrfoundation.org/job/generic-release-homebrew_bottle_builder/294/) https://build.osrfoundation.org/job/generic-release-homebrew_bottle_builder/294/

**Comment by chapulina** [comment]
New Mojave: [Build Status](https://build.osrfoundation.org/job/generic-release-homebrew_bottle_builder/label=osx_mojave/295/)

**Comment by chapulina** [comment]
@scpeters , the latest Mojave bottle you started is green, does this mean we're ready to :ship: ?

**Comment by scpeters** [comment]
we have to wait for the commit with the bottles, which is there now. then I like to make sure the travis and azure CI are happy, which basically check that the bottle got uploaded

**Comment by scpeters** [comment]
azure failed one build because of a problem with the ignition-launch1 formula, that I fixed already on `master`, but this wasn't rebased to use it

**Pull request merged**
