### PR TITLE
ignition-gui3: depend on msgs5 and transport8

### PR DESCRIPTION
**Pull request by chapulina**
See https://bitbucket.org/ignitionrobotics/ign-gui/pull-requests/225/

### CODE REVIEW

**Comment by scpeters** [comment]
[Build Status](https://build.osrfoundation.org/job/generic-release-homebrew_bottle_builder/517/) https://build.osrfoundation.org/job/generic-release-homebrew_bottle_builder/517/

**Comment by chapulina** [comment]
It looks like the bottle building failed at the [test](https://build.osrfoundation.org/job/generic-release-homebrew_bottle_builder/label=osx_mojave/517/console):

~~~
==> brew test --verbose ignition-gazebo3
==> FAILED
~~~

But I'm not sure why

**Comment by scpeters** [comment]
it also failed during `brew test ignition-gui3`, but I think that's a flaky test

**Comment by scpeters** [comment]
I think the `ignition-gazebo3`  test is caused when something links against multiple versions of `ignition-msgs`. I think we should disable bottles for `ignition-gazebo3` on master and rebase this pull request; that will cause it to skip the ignition-gazebo3 test

**Comment by scpeters** [comment]
ignition-gazebo3 bottles disabled in 926a13faa4719c74c0a4473ec7cb2ce2e9c0b2ba

**Comment by scpeters** [comment]
I just rebased and will restart the build

**Pull request merged**
