### PR TITLE
Use cartr/qt4/qt@4 instead of qt4-no-webkit

### PR DESCRIPTION
**Pull request by scpeters**
There is a 3rd-party homebrew tap that provides bottles of qt4 without webkit, which was my main objection to using it previously.

### CODE REVIEW

**Comment by j-rivero** [comment]
`Error: No available formula with the name "cartr/qt4/qt@4" ` is this expected in the travis testing?

**Comment by scpeters** [comment]
This is an upstream problem; I'm making a pull request to brew to fix it

**Comment by scpeters** [comment]
I just submitted https://github.com/Homebrew/brew/issues/2614 which should fix this build

**Comment by scpeters** [comment]
Actually, the proper fix is in https://github.com/Homebrew/homebrew-test-bot/pull/86

**Comment by scpeters** [comment]
I merged the update to gazebo7 with new bottles in #243, so now this can be merged since it is just updating formulae

**Pull request merged**
