### PR TITLE
ign-gui4: update commit

### PR DESCRIPTION
**Pull request by chapulina**
This is needed by https://github.com/ignitionrobotics/ign-gazebo/pull/144

### CODE REVIEW

**Comment by scpeters** [comment]
I just added revision bumps for the dome formula with missing bottles, so this should be ready for another build

**Comment by chapulina** [comment]
Thanks, @scpeters ! Can I go ahead and trigger this? https://build.osrfoundation.org/job/generic-release-homebrew_bottle_builder/

**Comment by scpeters** [comment]
> Can I go ahead and trigger this?

@j-rivero was running some builds yesterday, so I was waiting for those to finish. This is ready to run, but we have been using the `restore_brew_vendor_rubt` branch of release-tools, so be sure to use that one

**Comment by j-rivero** [comment]
Ongoing [Build Status](https://build.osrfoundation.org/job/generic-release-homebrew_bottle_builder/842/)

**Comment by scpeters** [comment]
[Build Status](https://build.osrfoundation.org/job/generic-release-homebrew_bottle_builder/849/) https://build.osrfoundation.org/job/generic-release-homebrew_bottle_builder/849/

**Comment by scpeters** [comment]
I redacted the revision bump to ignition-launch3 in 6fa8b81 because that formula searches for ign-gui3 and doesn't work.

**Pull request merged**
