### PR TITLE
Add OGRE2.3 formula

### PR DESCRIPTION
**Pull request by mjcarroll**
Signed-off-by: Michael Carroll <michael@openrobotics.org>

### CODE REVIEW

**Comment by mjcarroll** [comment]
build bottle

**Comment by scpeters** [comment]
should this depend on boost?

**Comment by mjcarroll** [comment]
> should this depend on boost?

I believe it optionally can, but doesn't need to (same as 2.2)

**Review by iche033 — COMMENTED** [review]
I ran into the same C++11 issue as the [bottle build jon on jenkins](https://build.osrfoundation.org/job/generic-release-homebrew_triggered_bottle_builder/label=osx_catalina/870/). To fix it I had to add this flag:

```
-DCMAKE_CXX_STANDARD=11
```

When testing locally, I also had to add:

```
-DCMAKE_CXX_COMPILER=clang++
```

This one may not be needed though since it looks like the jenkins build got further without this set

**Comment by mjcarroll** [comment]
build bottle

**Comment by mjcarroll** [comment]
build bottle

**Comment by mjcarroll** [comment]
@scpeters not sure why setting a different branch causes this to fail audit.  I just changed to to `master` to get it past that point?

```
  * HEAD: Use `branch: "master"` to specify the default branch
```

**Comment by mjcarroll** [comment]
build bottle

**Comment by scpeters** [comment]
build bottle

**Pull request merged**
