### PR TITLE
ignition-common 0.2.0

### PR DESCRIPTION
**Pull request by osrfbuild**

### CODE REVIEW

**Comment by scpeters** [comment]
The shasum was wrong for some reason, so I fixed that in e3e7aca4dec207ca7e9cf19a1791bc3c911b0f6f

I also added the bottle blocks from #224 in c53d9df36acb93b11130bbb282688849d1269619

**Comment by scpeters** [comment]
So I think we just need to re-trigger the bottle builder jobs

**Comment by j-rivero** [comment]
> The shasum was wrong for some reason, so I fixed that in e3e7aca

That was my fault, the problem came from my problems uploading to S3.

> So I think we just need to re-trigger the bottle builder jobs

Let me try it again.

**Comment by j-rivero** [comment]
we needs to merge first pr #227

**Comment by scpeters** [comment]
I think we should add that commit to this PR, since the patch is needed for version 0.1.0

**Comment by scpeters** [comment]
I just cherry-picked it in 1f9cee0d52915c21b669f50e8aa55cf5d1eb0261

**Comment by scpeters** [comment]
I guess we need an ignition-math 3.1.0 release since ignition-common 0.2.0 needs Color.hh

**Comment by j-rivero** [comment]
> I guess we need an ignition-math 3.1.0 release since ignition-common 0.2.0 needs Color.hh

yeeep!

**Pull request merged**
