### PR TITLE
Update gazebo11.rb to build against ffmpeg@6 instead of ffmpeg (v. 7)

### PR DESCRIPTION
**Pull request by gmerlino**
Fixes build failure.

### CODE REVIEW

**Comment by scpeters** [comment]
Thanks for the suggestion; I think this would work, but we'd have to set some environment variables in order to compile gazebo from source (see https://github.com/gazebo-tooling/release-tools/pull/636). Since we've already merged support for ffmpeg 7 in https://github.com/gazebosim/gz-common/pull/329, I'm inclined to port that patch to gazebo11

**Comment by scpeters** [comment]
> Thanks for the suggestion; I think this would work, but we'd have to set some environment variables in order to compile gazebo from source (see [gazebo-tooling/release-tools#636](https://github.com/gazebo-tooling/release-tools/pull/636)). Since we've already merged support for ffmpeg 7 in [gazebosim/gz-common#329](https://github.com/gazebosim/gz-common/pull/329), I'm inclined to port that patch to gazebo11

I've attempted a patch in https://github.com/gazebosim/gazebo-classic/pull/3380

**Comment by gmerlino** [comment]
> Thanks for the suggestion; I think this would work, but we'd have to set some environment variables in order to compile gazebo from source (see [gazebo-tooling/release-tools#636](https://github.com/gazebo-tooling/release-tools/pull/636)). Since we've already merged support for ffmpeg 7 in [gazebosim/gz-common#329](https://github.com/gazebosim/gz-common/pull/329), I'm inclined to port that patch to gazebo11

I see your point about the envs (PKG_CONFIG_PATH I reckon). Building upon install works without any additional changes to the formula, though.

**Comment by scpeters** [comment]
Thanks for your suggestion; this is a valid approach, but I've chosen to rebuild with the patch from https://github.com/gazebosim/gazebo-classic/pull/3380 in https://github.com/osrf/homebrew-simulation/pull/2636, so I'm going to close this now

**Pull request closed without merging**
