### PR TITLE
gz-physics6 6.5.0

### PR DESCRIPTION
**Pull request by osrfbuild**

### CODE REVIEW

**Comment by j-rivero** [comment]
@osrfbuild build bottles

**Comment by j-rivero** [comment]
@osrfbuild build bottles

**Comment by scpeters** [comment]
build bottle

**Comment by scpeters** [comment]
build bottle

**Comment by scpeters** [comment]
this build has started, but it didn't seem to update the build status:

* [Build Status](https://build.osrfoundation.org/job/generic-release-homebrew_triggered_bottle_builder/1264/) https://build.osrfoundation.org/job/generic-release-homebrew_triggered_bottle_builder/1264/

**Pull request merged**
