### PR TITLE
ignition-common4 4.0.0~pre1

### PR DESCRIPTION
**Pull request by osrfbuild**

### CODE REVIEW

**Comment by chapulina** [comment]
build bottle

**Comment by scpeters** [comment]
build bottle

**Comment by scpeters** [comment]
build bottle

**Comment by scpeters** [comment]
a bottle failed to upload, so I retriggered the upload job:

* https://build.osrfoundation.org/job/repository_uploader_packages/10879/
* https://build.osrfoundation.org/job/repository_uploader_packages/10880/

**Comment by scpeters** [comment]
build bottle

**Comment by scpeters** [comment]
ABI was changed in this prerelease, so we need to build some downstream packages

**Comment by scpeters** [comment]
build bottle

**Pull request merged**
