### PR TITLE
ignition-gazebo5: update edifice dependencies

### PR DESCRIPTION
**Pull request by chapulina**
Addressing https://github.com/ignition-tooling/release-tools/issues/362

Uses commit from https://github.com/ignitionrobotics/ign-gazebo/pull/546/commits

### CODE REVIEW

**Comment by scpeters** [comment]
build bottle

**Comment by scpeters** [comment]
build bottle

**Comment by scpeters** [comment]
build bottle

**Comment by chapulina** [comment]
Bottle updated :tada:

**Pull request merged**
