### PR TITLE
Bump revision on gazebo9 formula

### PR DESCRIPTION
**Pull request by sloretz**
Bumping revision to rebuild the bottle because dartsim version was bumped from  6.3 to 6.4

### CODE REVIEW

**Comment by sloretz** [comment]
[Build Status](https://build.osrfoundation.org/view/os_homebrew/job/generic-release-homebrew_bottle_builder-elcapitan/201/) El Capitan

**Comment by sloretz** [comment]
Looks like all of the jobs passed. @scpeters I think this is ready to be squash/merged. If it looks good would you mind merging it? I don't have permissions on the `osrf` organization.

**Comment by scpeters** [comment]
looks good to me! @sloretz do you want to do the honors of squash and merge?

**Comment by scpeters** [comment]
how did I not read your comment, sorry

I'll add permissions for you

**Pull request merged**
