### PR TITLE
ignition-launch3 3.0.0~pre1

### PR DESCRIPTION
**Pull request by osrfbuild**

### CODE REVIEW

**Comment by chapulina** [comment]
build bottle

**Comment by chapulina** [comment]
```
==> SKIPPED osrf/simulation/ignition-launch3
macOS Mojave or newer is required.
```

**Comment by scpeters** [comment]
here's the important part:

~~~
==> brew fetch --retry osrf/simulation/ignition-launch3 --build-bottle
==> FAILED
==> Fetching ignition-launch3 from osrf/simulation
==> Downloading https://osrf-distributions.s3.amazonaws.com/ign-launch/releases/ignition-launch3-3.0.0~pre1.tar.bz2
Downloaded to: /Users/jenkins/Library/Caches/Homebrew/downloads/9d862db51c87673acdd6b69b4fedada6d9f3e4b388ca7db155444021345d48f2--ignition-launch3-3.0.0~pre1.tar.bz2
SHA256: 693321873ffb38d2979011966c36c7a8ebf80a836380211f151732d01522b241
==> Retrying download
==> Downloading https://osrf-distributions.s3.amazonaws.com/ign-launch/releases/ignition-launch3-3.0.0~pre1.tar.bz2
Warning: Formula reports different SHA256: c5608083c551d4121f176cdf58d921b71f37ed4625277bb484b839429373a649
Downloaded to: /Users/jenkins/Library/Caches/Homebrew/downloads/9d862db51c87673acdd6b69b4fedada6d9f3e4b388ca7db155444021345d48f2--ignition-launch3-3.0.0~pre1.tar.bz2
SHA256: 693321873ffb38d2979011966c36c7a8ebf80a836380211f151732d01522b241
~~~

**Comment by scpeters** [comment]
probably multiple release.py calls? [Build Status](https://build.osrfoundation.org/job/generic-release-homebrew_pull_request_updater/719/) https://build.osrfoundation.org/job/generic-release-homebrew_pull_request_updater/719/

**Comment by chapulina** [comment]
> probably multiple release.py calls?

Ah true, before and after https://github.com/ignition-release/ign-launch3-release/pull/1, for revisions `-1` and `-2`

**Comment by scpeters** [comment]
we really need to fix https://github.com/ignition-tooling/release-tools/issues/274

**Comment by chapulina** [comment]
build bottle

**Comment by scpeters** [comment]
the key is fixing the tarball `sha256`: https://github.com/osrf/homebrew-simulation/pull/1156/commits/57fa5defcce8becd59138250d2f01742c447e6ab

**Comment by scpeters** [comment]
build bottle

**Comment by chapulina** [comment]
build bottle

**Pull request merged**
