### PR TITLE
Use ignition-math3 in sdformat

### PR DESCRIPTION
**Pull request by j-rivero**
According with: https://bitbucket.org/osrf/sdformat/pull-requests/297

### CODE REVIEW

**Comment by chapulina** [comment]
I'm not sure what's the difference between the two Travis jobs, is it expected that the `/pr` one fails?

**Comment by j-rivero** [comment]
Same scenario that the one I described in [the ignition-msgs PR](https://github.com/osrf/homebrew-simulation/pull/197#issuecomment-273548384).

**Comment by scpeters** [comment]
It needs new bottles, as discussed in #197

**Comment by scpeters** [comment]
it will probably be easier too if this was merged into #197, so the bottles could just be built once

**Comment by chapulina** [comment]
This PR should be updated for sdf5, right?

**Comment by j-rivero** [comment]
> This PR should be updated for sdf5, right?

Right. Let's continue in #197 and a new PR for sdformat5

**Pull request closed without merging**
