### PR TITLE
Remove bottles broken by gdal 3.7.1

### PR DESCRIPTION
**Pull request by azeey**
Part of #2328

### CODE REVIEW

**Comment by azeey** [comment]
Testing: [Build Status](https://build.osrfoundation.org/job/ignition_gazebo-ci-main-homebrew-amd64/186/)

**Comment by azeey** [comment]
That failed. I think I specified this branch instead of the PR URL. Trying again
[Build Status](https://build.osrfoundation.org/job/ignition_gazebo-ci-main-homebrew-amd64/187/)

**Comment by azeey** [comment]
I also tried creating a PR with a matching branch (https://github.com/gazebosim/gz-sim/pull/2071), but that didn't seem to work either 😢. I'll go ahead and merge and do another test.

**Comment by azeey** [comment]
Another test: [Build Status](https://build.osrfoundation.org/job/ignition_gazebo-ci-main-homebrew-amd64/188/)

**Comment by scpeters** [comment]
> I also tried creating a PR with a matching branch ([gazebosim/gz-sim#2071](https://github.com/gazebosim/gz-sim/pull/2071)), but that didn't seem to work either 😢. I'll go ahead and merge and do another test.

to use the matching branch trick, the branch name needs to start with `ci_matching_branch/`, similar to https://github.com/gazebosim/gz-transport/pull/416

**Pull request merged**
