### PR TITLE
ignition-cmake2 2.17.2

### PR DESCRIPTION
**Pull request by osrfbuild**

### CODE REVIEW

**Comment by j-rivero** [comment]
@osrfbuild build packages

**Comment by j-rivero** [comment]
build bottle

**Comment by j-rivero** [comment]
build bottle

**Comment by scpeters** [comment]
the build was failing to validate the gazebo11 bottle due to #2649. I've added a patch from https://github.com/gazebosim/gazebo-classic/pull/3386 and bumped the gazebo11 revision, which should fix things here

**Comment by scpeters** [comment]
build bottle

**Pull request merged**
