### PR TITLE
ignition-sensors3 3.6.0

### PR DESCRIPTION
**Pull request by osrfbuild**

### CODE REVIEW

**Comment by azeey** [comment]
@osrf-jenkins build bottle

**Comment by scpeters** [comment]
a patch needs to be removed

**Comment by scpeters** [comment]
do you mind if I merge https://github.com/osrf/homebrew-simulation/pull/2526 before this?

**Comment by scpeters** [comment]
I'll go ahead and merge it now and then work on the rest of these

**Comment by azeey** [comment]
> do you mind if I merge #2526 before this?

No problem.

**Comment by scpeters** [comment]
build bottle

**Pull request merged**
