### PR TITLE
ogre1.9: add placeholder bottle block

### PR DESCRIPTION
**Pull request by scpeters**

### CODE REVIEW

**Comment by scpeters** [comment]
fixes #170

**Comment by LorenzMeier** [comment]
Yeah, but I'm on sierra, like many other folks 8). The dirty little trick that works reliably for me is to just copy the line for el capitan for sierra.

**Comment by scpeters** [comment]
that may work for ogre, but gazebo7 and earlier won't work on 10.12 due to a lack of qt4 (#160)

we are migrating gazebo8 to qt5 (still in process) and will release in January

**Comment by LorenzMeier** [comment]
As I said we can help with bottle building locally. I can build a working bottle on my machine for sierra.

**Comment by scpeters** [comment]
If you can test the formulae that can use the same bottles on sierra as el_capitan and open a pull request that bumps the formula revision and adds a new line in the bottle block for sierra (much like #174), then I'll be happy to copy the bottles over and/or upload bottles from your team.

As I mentioned, though, an important gazebo7 dependency is not available on sierra, so hopefully gazebo8 will work for your team.

**Pull request merged**
