### PR TITLE
ignition-gui3 depend on ignition-rendering3

### PR DESCRIPTION
**Pull request by chapulina**
Goes with this PR:

https://bitbucket.org/ignitionrobotics/ign-gui/pull-requests/221/depend-on-ign-rendering3/

### CODE REVIEW

**Comment by scpeters** [comment]
we need a real formula for ign-rendering3, currently it's just an alias to rendering2

**Comment by scpeters** [comment]
similar to #672

**Comment by chapulina** [comment]
neds #804

**Comment by scpeters** [comment]
[Build Status](https://build.osrfoundation.org/job/generic-release-homebrew_bottle_builder/433/) https://build.osrfoundation.org/job/generic-release-homebrew_bottle_builder/433/

**Pull request merged**
