### PR TITLE
Fortress: build monterey bottles final part

### PR DESCRIPTION
**Pull request by scpeters**
Add small change to several formulae (head)
so bottle builds for macOS Monterey can be
triggered.

* ign-gazebo6, ign-launch5, ign-fortress

Signed-off-by: Steve Peters <scpeters@openrobotics.org>

### CODE REVIEW

**Review by j-rivero — APPROVED** [review]

**Comment by scpeters** [comment]
build bottle
brew-bot-tag: build-for-new-distro-monterey

**Comment by scpeters** [comment]
only the ign-physics5 bottle worked. I'll try again

build bottle
brew-bot-tag: build-for-new-distro-monterey

**Comment by scpeters** [comment]
build bottle
brew-bot-tag: build-for-new-distro-monterey

**Comment by scpeters** [comment]
build bottle
brew-bot-tag: build-for-new-distro-monterey

**Comment by scpeters** [comment]
build bottle
brew-bot-tag: build-for-new-distro-monterey

**Pull request merged**
