### PR TITLE
ignition-gazebo2 2.26.0

### PR DESCRIPTION
**Pull request by osrfbuild**

### CODE REVIEW

**Comment by chapulina** [comment]
build bottle

**Comment by chapulina** [comment]
build bottle

**Comment by scpeters** [comment]
build bottle

**Comment by scpeters** [comment]
it's failing with a seg-fault during doc generation, similar to https://github.com/ignitionrobotics/ign-gazebo/pull/517#issuecomment-752171267

**Comment by scpeters** [comment]
build bottle

**Pull request merged**
