### PR TITLE
ignition-transport9: new formula

### PR DESCRIPTION
**Pull request by chapulina**
Remove alias and add new formula that depends on `ign-msgs6`. I took the last commit of https://github.com/ignitionrobotics/ign-transport/pull/149/

This is broken off https://github.com/osrf/homebrew-simulation/pull/1063 so we can make the changes incrementally.

### CODE REVIEW

**Comment by chapulina** [comment]
CI is failing asking for a license. I didn't find any license information on any formula here, is this a new requirement? @scpeters , please advise.

```
==> brew audit osrf/simulation/ignition-transport9 --online --new-formula
==> FAILED
Error: 1 problem in 1 formula detected
osrf/simulation/ignition-transport9:
  * No license specified for package.
```

**Comment by chapulina** [comment]
Merging!

**Comment by scpeters** [comment]
> CI is failing asking for a license. I didn't find any license information on any formula here, is this a new requirement?

sorry I missed this earlier

yes, this is a new requirement, but only for new formulae. I'll update the existing formulae

**Comment by scpeters** [comment]
also, when adding new formulae, we can remove the old alias, but it's also a good time to just add a new alias for the next major version. I'll take care of it for this formula

**Comment by scpeters** [comment]
> also, when adding new formulae, we can remove the old alias, but it's also a good time to just add a new alias for the next major version. I'll take care of it for this formula

a08e96005b8e2fb3acaa908bbaa720276c3fb6ca

**Pull request merged**
