### PR TITLE
ignition-gui6 6.1.0

### PR DESCRIPTION
**Pull request by osrfbuild**

### CODE REVIEW

**Comment by chapulina** [comment]
build bottle

**Review by scpeters — CHANGES_REQUESTED** [review]
the big_sur bottle didn't build

don't merge this yet

**Comment by scpeters** [comment]
hmm it looks like this first happened with https://github.com/osrf/homebrew-simulation/pull/1660

**Comment by scpeters** [comment]
> hmm it looks like this first happened with #1660

we'll fix this later, just merge for now

**Pull request merged**
