### PR TITLE
ignition-sensors2: use msgs4/transport7

### PR DESCRIPTION
**Pull request by scpeters**

### CODE REVIEW

**Comment by scpeters** [comment]
[Build Status](https://build.osrfoundation.org/job/generic-release-homebrew_bottle_builder/255/) https://build.osrfoundation.org/job/generic-release-homebrew_bottle_builder/255/

**Comment by scpeters** [comment]
~~~
/tmp/ignition-sensors2-20190415-48508-1otf31k/ignitionrobotics-ign-sensors-fe0232e17b05/src/CameraSensor.cc:295:7: error: no member named 'set_pixel_format_type' in 'ignition::msgs::Image'
  msg.set_pixel_format_type(msgsPixelFormat);
  ~~~ ^
~~~

@chapulina maybe msgs4 needs to be updated too?

**Comment by chapulina** [comment]
Oh yeah it does

**Comment by scpeters** [comment]
the mojave bottles are building but the job fails because ign-gazebo2 fails to install its dependencies due to the conflicts between msgs3/msgs4

* https://bitbucket.org/ignitionrobotics/ign-msgs/issues/24/unversioned-files-lib-ruby-ignition-msgs
* https://bitbucket.org/ignitionrobotics/ign-msgs/issues/27/install-ruby-messages-on-versioned

if we don't fix that msgs conflict, then we need to change all the dependencies at once

**Comment by scpeters** [comment]
trying to fix the msgs3/4 conflict in:

* https://bitbucket.org/ignitionrobotics/ign-msgs/pull-requests/109

updated msgs4 to use that pull request and removed the conflict. I've started a new bottle build, that will hopefully pass with this msgs commit

* [Build Status](https://build.osrfoundation.org/job/generic-release-homebrew_bottle_builder/258/) https://build.osrfoundation.org/view/os_homebrew/job/generic-release-homebrew_bottle_builder/258/

**Comment by scpeters** [comment]
travis error was spurious

**Pull request merged**
