### PR TITLE
gz-math7 7.3.0

### PR DESCRIPTION
**Pull request by osrfbuild**

### CODE REVIEW

**Comment by azeey** [comment]
@osrf-jenkins build bottle

**Comment by scpeters** [comment]
not sure why that comment didn't start a build

**Comment by scpeters** [comment]
build bottle

**Comment by azeey** [comment]
hmm, I thought it built and updated the hash

**Comment by scpeters** [comment]
now it's going

**Comment by scpeters** [comment]
> hmm, I thought it built and updated the hash

I don't any gz-math7 builds in the jenkins job history before this one:

* https://build.osrfoundation.org/job/generic-release-homebrew_triggered_bottle_builder/1250/

**Comment by azeey** [comment]
> > hmm, I thought it built and updated the hash
> 
> I don't see any gz-math7 builds in the jenkins job history before this one:
> 
> * https://build.osrfoundation.org/job/generic-release-homebrew_triggered_bottle_builder/1250/

Yeah. It's weird that the hash was updated without a bottle being built. A problem for another day...

**Comment by scpeters** [comment]
> > > hmm, I thought it built and updated the hash
> > 
> > 
> > I don't see any gz-math7 builds in the jenkins job history before this one:
> > 
> > * https://build.osrfoundation.org/job/generic-release-homebrew_triggered_bottle_builder/1250/
> 
> Yeah. It's weird that the hash was updated without a bottle being built. A problem for another day...

the tarball `sha256` was updated by the job triggered by release.py that opened the pull request. the bottle hashes haven't been touched yet

**Comment by azeey** [comment]
> not sure why that comment didn't start a build

I didn't wait till the brew test-bot action finished. Would that be an issue?

**Comment by scpeters** [comment]
now it appears there was a second jenkins job run. weird stuff today. it's working now though so I'll merge

**Comment by scpeters** [comment]
> > not sure why that comment didn't start a build
> 
> I didn't wait till the brew test-bot action finished. Would that be an issue?

no that shouldn't affect it

**Pull request merged**
