### PR TITLE
gz-common6: disable pkg-config test

### PR DESCRIPTION
**Pull request by azeey**
bottles failed to build for gz-common6 in #2773 due to a test failure.

### CODE REVIEW

**Comment by azeey** [comment]
build bottle

**Comment by scpeters** [comment]
build bottle

**Comment by scpeters** [comment]
the cmake test works, but the pkg-config test is broken; I don't see `fmt` listed as a pkg-config dependency; I'm guessing that would need to be fixed in order to re-enable it

**Comment by scpeters** [comment]
build bottle

**Pull request merged**
