### PR TITLE
ignition-utils: version 1 instead of 0

### PR DESCRIPTION
**Pull request by chapulina**
@scpeters , I'm not sure if moving the file like I did is ok, or if you'd prefer to keep version zero and copy over to version 1.

Uses the commit from https://github.com/ignitionrobotics/ign-utils/pull/6

### CODE REVIEW

**Comment by scpeters** [comment]
this looks fine to me, since nothing has been released using utils0

**Comment by scpeters** [comment]
I made a comment about the cmake project name: https://github.com/ignitionrobotics/ign-utils/pull/6/files#r562252181

**Comment by chapulina** [comment]
build bottle

**Comment by chapulina** [comment]
`BuildError: Failed executing: pkg-config ignition-utils1`... Version 1s are a pain...

**Comment by scpeters** [comment]
I'll test it manually

**Comment by scpeters** [comment]
we forgot to update the commit to https://github.com/ignitionrobotics/ign-utils/pull/6/commits/6d6a54935c8f8ea443c150f5bfb375adfb2b2e28 as well; I'll do it now

**Comment by scpeters** [comment]
build bottle

**Pull request merged**
