### PR TITLE
ignition-transport8: depend on ign-msgs5

### PR DESCRIPTION
**Pull request by chapulina**
See https://bitbucket.org/ignitionrobotics/ign-transport/pull-requests/402/

### CODE REVIEW

**Comment by chapulina** [comment]
Bottle builder triggered: [Build Status](https://build.osrfoundation.org/job/generic-release-homebrew_bottle_builder/515/)

**Comment by scpeters** [comment]
the bottle build failed with a complaint about pkg-config

I'm going to see if I can reproduce it on the build machine

**Comment by scpeters** [comment]
the ign-transport branch this is built from still has major version 7, which is why it failed to find the pkg-config file for ignition-transport8

**Comment by chapulina** [comment]
Woops! Bumped in `ign-transport`, updated the commit and triggered new bottle: [Build Status](https://build.osrfoundation.org/job/generic-release-homebrew_bottle_builder/516/)

**Comment by scpeters** [comment]
looks great, merging

**Pull request merged**
