### PR TITLE
[DONTMERGE] ignition-plugin0: revision bump

### PR DESCRIPTION
**Pull request by scpeters**
Testing pull request for @j-rivero, don't need to merge it

### CODE REVIEW

**Comment by j-rivero** [comment]
test bottle

**Comment by j-rivero** [comment]
test bottle

**Comment by scpeters** [comment]
build bottle

**Comment by scpeters** [comment]
build bottle

**Comment by scpeters** [comment]
we can open a different one if we need to do more testing. closing this

**Pull request closed without merging**
