### PR TITLE
gazebo9 bump for new DART

### PR DESCRIPTION
**Pull request by j-rivero**
part of  #1665

### CODE REVIEW

**Comment by j-rivero** [comment]
build bottle

**Comment by j-rivero** [comment]
Somehow the [builder job](https://build.osrfoundation.org/job/generic-release-homebrew_triggered_bottle_builder/657/label=osx_catalina/console) is not producing any bottle. @scpeters do you have any hint about what could be happening?

**Comment by scpeters** [comment]
something changed recently in homebrew-test-bot that will skip bottling a formula if any of its dependencies are not bottled for that version of macOS. Previously it would use bottles from older macOS distros. I believe simbody and ignition-math4 are blocking gazebo9

There is a special way to use test-bot with the `--keep-old` flag to build bottles for a new distro only without bumping a revision. We should make a new jenkins job for this that has a package name (or names) and a single macOS distro name to use (such as bigsur or catalina) that will be used to construct the jenkins node label to use (osx_bigsur or osx_catalina). I'll open an issue for this on release-tools

**Comment by scpeters** [comment]
> something changed recently in homebrew-test-bot that will skip bottling a formula if any of its dependencies are not bottled for that version of macOS. Previously it would use bottles from older macOS distros. I believe simbody and ignition-math4 are blocking gazebo9
> 
> There is a special way to use test-bot with the `--keep-old` flag to build bottles for a new distro only without bumping a revision. We should make a new jenkins job for this that has a package name (or names) and a single macOS distro name to use (such as bigsur or catalina) that will be used to construct the jenkins node label to use (osx_bigsur or osx_catalina). I'll open an issue for this on release-tools

https://github.com/ignition-tooling/release-tools/issues/555

**Comment by scpeters** [comment]
I'll build again, though I expect it to fail since we haven't built bottles yet from #1675  to see if https://github.com/Homebrew/homebrew-test-bot/pull/717 gives useful console output

build bottle

**Comment by scpeters** [comment]
build bottle

**Comment by scpeters** [comment]
build bottle

**Pull request merged**
