### PR TITLE
sdformat9 9.2.0

### PR DESCRIPTION
**Pull request by osrfbuild**

### CODE REVIEW

**Comment by scpeters** [comment]
bottle build failed due to a homebrew bug

I'll restart the build after it's resolved

**Comment by scpeters** [comment]
first build

[Build Status](https://build.osrfoundation.org/job/generic-release-homebrew_bottle_builder/724/) https://build.osrfoundation.org/job/generic-release-homebrew_bottle_builder/724/

**Comment by chapulina** [comment]
I think the latest build worked? [Build Status](https://build.osrfoundation.org/job/generic-release-homebrew_bottle_builder/label=osx_highsierra/725/)

**Comment by scpeters** [comment]
yeah, but mojave failed [Build Status](https://build.osrfoundation.org/job/generic-release-homebrew_bottle_builder/label=osx_mojave/725/)

I'll try building again to see if mojave works the 2nd time

**Comment by scpeters** [comment]
[Build Status](https://build.osrfoundation.org/job/generic-release-homebrew_bottle_builder/726/) https://build.osrfoundation.org/job/generic-release-homebrew_bottle_builder/726/

**Comment by scpeters** [comment]
GitHub actions is failing because of that homebrew bug, but I think it's safe to merge

**Pull request merged**
