### PR TITLE
gazebo11: use new tbb and recent patch

### PR DESCRIPTION
**Pull request by scpeters**
Use patch from https://github.com/osrf/gazebo/pull/3174 and switch to the current version of `tbb`.

### CODE REVIEW

**Comment by scpeters** [comment]
build bottle

**Comment by scpeters** [comment]
build bottle

**Comment by Blast545** [comment]
:man_farmer: It seems this PR caused a build regression in the homewbrew gazebo11 buildfarm, see:
https://build.osrfoundation.org/job/gazebo-ci-gazebo11-homebrew-amd64/129/

It seems the patch is not being applied properly, as there are a lot of `tbb.h` deprecation warnings in the log.

**Comment by scpeters** [comment]
> 👨‍🌾 It seems this PR caused a build regression in the homewbrew gazebo11 buildfarm, see: https://build.osrfoundation.org/job/gazebo-ci-gazebo11-homebrew-amd64/129/
> 
> It seems the patch is not being applied properly, as there are a lot of `tbb.h` deprecation warnings in the log.

that build ran before this was merged. I think https://build.osrfoundation.org/job/gazebo-ci-gazebo11-homebrew-amd64/130/ may have better luck

**Comment by traversaro** [comment]
> :man_farmer: It seems this PR caused a build regression in the homewbrew gazebo11 buildfarm, see:
> https://build.osrfoundation.org/job/gazebo-ci-gazebo11-homebrew-amd64/129/
> 
> It seems the patch is not being applied properly, as there are a lot of `tbb.h` deprecation warnings in the log.

To be honest I did not check if in the tbb >= 2021 case there where zero deprecation warnings, so the issue could be in the patch as it is, not in how it is applied.

**Pull request merged**
