### PR TITLE
gz-physics6 6.4.0

### PR DESCRIPTION
**Pull request by osrfbuild**

### CODE REVIEW

**Comment by azeey** [comment]
@osrf-jenkins build bottle

**Comment by azeey** [comment]
@osrf-jenkins build bottle

**Comment by azeey** [comment]
@osrf-jenkins build bottle

**Comment by azeey** [comment]
The bottle build is failing with the following error. I've tried both on mac-eight and mac-six.
```
==> brew doctor
All steps passed!
+ brew test-bot --tap=osrf/simulation --fail-fast --only-formulae --root-url=https://osrf-distributions.s3.amazonaws.com/bottles-simulation
==> Using Homebrew/homebrew-test-bot 430b676 (Merge pull request #921 from Homebrew/safer_api_tests)
==> Using Homebrew/brew 4.0.19-9-g8aaf99e1d (Merge pull request #15475 from reitermarkus/fetch-wrong-method)
==> Using Homebrew/homebrew-core 5132eac5535 (Merge pull request #131657 from BrewTestBot/brew-pip-audit-bzt-1684811619)
==> Testing osrf/homebrew-simulation ( bb936f9 (Merge branch 'master' into gz-physics6_6.4.0):

==> Running FormulaeDetect#detect_formulae!
Error: No known CI provider detected! If you are using GitHub Actions then we cannot find the expected environment variables! Check you have e.g. exported them to a Docker container.
    url               (blank)
    tap origin/master 0bcf7ac (README: add garden CI badges (#2266))
    HEAD              bb936f9 (Merge branch 'master' into gz-physics6_6.4.0)
    diff_start_sha1   bb936f90f47917cdc48eeeba913c0065fa883743
    diff_end_sha1     bb936f90f47917cdc48eeeba913c0065fa883743
Usage: brew test-bot [options] [formula]

Tests the full lifecycle of a Homebrew change to a tap (Git repository). For
example, for a GitHub Actions pull request that changes a formula brew
test-bot will ensure the system is cleaned and set up to test the formula,
install the formula, run various tests and checks on it, bottle (package) the
binaries and test formulae that depend on it to ensure they aren't broken by
these changes.
```

**Comment by scpeters** [comment]
so the builder job finished successfully:

* [Build Status](https://build.osrfoundation.org/job/generic-release-homebrew_triggered_bottle_builder/1185/) https://build.osrfoundation.org/job/generic-release-homebrew_triggered_bottle_builder/1185/

and started two downstream jobs:

* https://build.osrfoundation.org/job/repository_uploader_packages/ (I'm not sure which build)
* [Build Status](https://build.osrfoundation.org/job/generic-release-homebrew_pr_bottle_hash_updater/1867/) https://build.osrfoundation.org/job/generic-release-homebrew_pr_bottle_hash_updater/1867/

I see the actual 6.4.0 bottles in s3, but the bottle hash update job failed; it's a bummer that it's flaky; at a minimum we should add it to the build status so we can see when it passes or fails

**Comment by azeey** [comment]
Ah, I didn't know that the hash updater was a separate job. 

>  at a minimum we should add it to the build status so we can see when it passes or fails

Agreed!

**Pull request merged**
