### PR TITLE
ignition-msgs7: new formula

### PR DESCRIPTION
**Pull request by nkoenig**
Signed-off-by: Nate Koenig <nate@openrobotics.org>

### CODE REVIEW

**Comment by chapulina** [comment]
build bottle

**Comment by scpeters** [comment]
build bottle

**Comment by scpeters** [comment]
for some reason it's failing to update the formulae bottle hash

* [Build Status](https://build.osrfoundation.org/job/generic-release-homebrew_pr_bottle_hash_updater/1122/) https://build.osrfoundation.org/job/generic-release-homebrew_pr_bottle_hash_updater/1122/

maybe because it's a new formula?

**Comment by chapulina** [comment]
> maybe because it's a new formula?

humm it worked for other new formulae, for example:

https://github.com/osrf/homebrew-simulation/pull/1193/commits/86be3f1df74a22dd51997b222ba430b7e7c5a415

I see some ruby errors on the log

**Comment by chapulina** [comment]
build bottle

**Comment by chapulina** [comment]
I thought it may be a spurious failure, because the failing command:

`Fetching gem metadata from https://rubygems.org/.........`

wasn't in the successful builds I looked at. So I triggered a new bottle build, but the same error is there. I don't know what would cause that extra fetch command.

**Comment by scpeters** [comment]
> I thought it may be a spurious failure, because the failing command:
> 
> `Fetching gem metadata from https://rubygems.org/.........`
> 
> wasn't in the successful builds I looked at. So I triggered a new bottle build, but the same error is there. I don't know what would cause that extra fetch command.

we are using some brew commands in Linux to update the bottle metadata, but something is failing to update properly.

I've just manually copied the bottle block listed in the console output of the failed job, so we can move forward with this PR

**Pull request merged**
