### PR TITLE
README: add edifice bottle badges

### PR DESCRIPTION
**Pull request by scpeters**

### CODE REVIEW

**Comment by chapulina** [comment]
Missing `ign-utils` and `libsdformat` :wink:

**Comment by scpeters** [comment]
> Missing `ign-utils` and `libsdformat`

so there is an ign-utils `install_bottle` job, but it's not part of the edifice view. I'll add its badge here

we don't have any `install_bottle` jobs for sdformat

**Comment by scpeters** [comment]
> > Missing `ign-utils` and `libsdformat`
> 
> so there is an ign-utils `install_bottle` job, but it's not part of the edifice view. I'll add its badge here
> 
> we don't have any `install_bottle` jobs for sdformat

https://github.com/ignition-tooling/release-tools/pull/460

**Comment by scpeters** [comment]
I've added badges for sdformat and ign-utils

**Review by chapulina — APPROVED** [review]

**Pull request merged**
