### PR TITLE
ignition-cmake1: use newer commit

### PR DESCRIPTION
**Pull request by dhood**
I'm looking for an updated version of ignition cmake for ignition rendering (see #457).

This converts it from using a released version to a particular commit, which might not be appropriate. Please advise if a new release is more appropriate instead

### CODE REVIEW

**Comment by chapulina** [comment]
`ign-rendering0` uses `ign-cmake1`, so I think [this file](https://github.com/osrf/homebrew-simulation/blob/master/ignition-cmake1.rb) should be edited instead, right?

And if you notice, that file uses a specific commit, so I think the approach taken here should be ok. This PR should be a good reference: https://github.com/osrf/homebrew-simulation/pull/393

**Comment by dhood** [comment]
thanks, I had looked at the log of [this build](https://build.osrfoundation.org/job/ignition_gui-ci-pr_any-homebrew-amd64/161/console) that referenced `ignition-cmake0`, but not closely enough to realise that's what it's _uninstalling_ :laughing: 
I'll swap to ignition-cmake1 as you suggested!

**Comment by chapulina** [comment]
Thanks for the change, it looks correct to me, but I don't know why Travis is failing... @scpeters , any ideas?

**Comment by j-rivero** [comment]
```
Downloading http://gazebosim.org/distributions/ign-cmake/releases/ignition-cmake1-1.1.0~20180731~9b5a8d7.el_capitan.bottle.tar.gz
curl: (22) The requested URL returned error: 406 Not Acceptable
==> Retrying download
==> Downloading http://gazebosim.org/distributions/ign-cmake/releases/ignition-cmake1-1.1.0~20180731~9b5a8d7.el_capitan.bottle.tar.gz
curl: (22) The requested URL returned error: 406 Not Acceptable
Error: Failed to download resource "ignition-cmake1"
Download failed: http://gazebosim.org/distributions/ign-cmake/releases/ignition-cmake1-1.1.0~20180731~9b5a8d7.el_capitan.bottle.tar.gz
==> FAILED
```
We are changing the version in this PR without touching the bottle information so the script is trying to locate the bottles with the new version and thus failing (they don't exist). We need one of both: or use release.py to release a new version for all our .debs and bottles (instead of this PR) or use Jenkins to build bottles using this PR (non affecting .debs). For this latest one, checkout the internal wiki information under the topic "Building bottles".

**Comment by scpeters** [comment]
Travis is failing because it expects the bottle to be updated. ign-cmake is a special case in that it only needs to build one bottles (for el_capitan) and then it can use it for the other OS versions.

So I recommend starting a bottle builder job for el capitan and passing this pull request URL. I'll do this tomorrow if no one else has done it before then.

* https://build.osrfoundation.org/view/os_homebrew/job/generic-release-homebrew_bottle_builder-elcapitan/

**Comment by dhood** [comment]
Thanks for the pointers! I didn't realise there was an internal wiki page about this: I squashed the commits in this PR as it suggested. I'm having login issues that I'm trying to sort out for the buildfarm to kick off the jobs

**Comment by dhood** [comment]
I got it to commit. But since 1.1.0 is released perhaps I was supposed to use version-0.00000001 like is done [here](https://github.com/osrf/homebrew-simulation/pull/450/files#diff-b43d236cccd0c3d7a7e8ec301d1e2237L5). Please review carefully!

**Comment by scpeters** [comment]
it looks great to me. thanks!

**Pull request merged**
