### PR TITLE
sdformat12: build main branch from source

### PR DESCRIPTION
**Pull request by scpeters**
This is a potential approach for solving #1314, motivated by https://github.com/ignitionrobotics/ign-gazebo/pull/811, which has failing CI since the sdformat12 formula is outdated.

### CODE REVIEW

**Comment by chapulina** [comment]
Trying it out here, I think:

[Build Status](https://build.osrfoundation.org/job/ignition_gazebo-ci-pr_any-homebrew-amd64/5626/)

I assume this doesn't need a `bottle build`, right?

**Comment by chapulina** [comment]
Humm that didn't work 

```
+ brew pull https://github.com/osrf/homebrew-simulation/pull/1459
Error: Unknown command: pull
```

I'm not sure how to test this :thinking:

**Comment by scpeters** [comment]
> Humm that didn't work
> 
> ```
> + brew pull https://github.com/osrf/homebrew-simulation/pull/1459
> Error: Unknown command: pull
> ```
> 
> I'm not sure how to test this 🤔

yeah, we can't test this in CI anymore. they disabled the `brew pull` command. we need to test it manually

**Comment by scpeters** [comment]
I've tested it manually. we can also try a binary approach:

build bottle

**Comment by scpeters** [comment]
> I've tested it manually

to clarify, it fixed https://github.com/ignitionrobotics/ign-gazebo/pull/811 in my manual testing

**Comment by chapulina** [comment]
Cool, I see the bottle has been uploaded! Merging!

**Pull request merged**
