### PR TITLE
👩‍🌾 ign-common3: revision bump for tinyxml2

### PR DESCRIPTION
**Pull request by chapulina**

### CODE REVIEW

**Comment by scpeters** [comment]
the jenkins bottle build failed since there is broken linkage for dependent packages ign-fuel-tools3 and ign-fuel-tools4

* [Build Status](https://build.osrfoundation.org/job/generic-release-homebrew_bottle_builder/label=osx_highsierra/688/) https://build.osrfoundation.org/job/generic-release-homebrew_bottle_builder/label=osx_highsierra/688/console

so we should bump those as well

**Comment by scpeters** [comment]
I bumped revisions on my mac laptop as follows:

~~~
cd `brew --repo`/Library/Taps/osrf/homebrew-simulation
git fetch origin
git checkout bump_common3
brew bump-revision ignition-fuel-tools3 --message="for tinyxml2"
brew bump-revision ignition-fuel-tools4 --message="for tinyxml2"
git push
~~~

**Comment by scpeters** [comment]
started a new bottle build job

[Build Status](https://build.osrfoundation.org/job/generic-release-homebrew_bottle_builder/692/) https://build.osrfoundation.org/job/generic-release-homebrew_bottle_builder/692/

**Comment by scpeters** [comment]
the job just found a new linking error with msgs5. I think it would be more time efficient to test on a dedicated machine to see which packages have broken linkage so we can bump them all at once, since that job took almost 2 hours

**Comment by chapulina** [comment]
Ok, tested locally and bumped everything that's affected by `common3`: f7b6719938a1e620908b4741b43da21e5528198e

**Comment by chapulina** [comment]
New build: [Build Status](https://build.osrfoundation.org/job/generic-release-homebrew_bottle_builder/693/)

**Comment by scpeters** [comment]
apparently gazebo4 and gui4 have bottles now too; I'll bump them and start a new build

**Comment by scpeters** [comment]
[Build Status](https://build.osrfoundation.org/job/generic-release-homebrew_bottle_builder/695/) https://build.osrfoundation.org/job/generic-release-homebrew_bottle_builder/695/

**Comment by chapulina** [comment]
Thanks for bumping more revisions, @scpeters . The latest build failed on Mojave, but I can't make sense of the logs.

**Comment by scpeters** [comment]
I've seen some recent pull requests on brew about detecting the correct SDK, and it looks like that's the problem here. I'll take a look at what has changed recently

**Comment by scpeters** [comment]
yes, I believe this happens on machines like sentinel, which have both the command-line tools and full Xcode installation

I wasn't able to reproduce on a  machine with only command-line tools

it may be related to these `ENV` variables set in the test

* https://github.com/osrf/homebrew-simulation/blob/master/Formula/ignition-common3.rb#L67-L68

**Comment by chapulina** [comment]
All checks passed! :raised_hands: :heavy_check_mark:

**Pull request merged**
