### PR TITLE
WIP: OS X Sierra Gazebo 7 support

### PR DESCRIPTION
**Pull request by LorenzMeier**
This is for initial feedback only. I will do a proper PR when you have moved the bottle files to your server. Watch the Qt version overlay, which needs to be osrf/simulation/qt (right now px4/simulation/qt).

Test instructions:
```
brew uninstall gazebo7
brew untap osrf/simulation
brew tap px4/simulation
brew update
brew install gazebo7
```

Bottles:
http://px4-travis.s3.amazonaws.com/toolchain/bottles/gazebo7-7.4.0_3.sierra.bottle.2.tar.gz
http://px4-travis.s3.amazonaws.com/toolchain/bottles/ignition-math2-2.6.0_1.sierra.bottle.1.tar.gz
http://px4-travis.s3.amazonaws.com/toolchain/bottles/ignition-transport-1.4.0_1.sierra.bottle.1.tar.gz
http://px4-travis.s3.amazonaws.com/toolchain/bottles/ogre-1.7.4_1.sierra.bottle.1.tar.gz
http://px4-travis.s3.amazonaws.com/toolchain/bottles/qt-4.8.7_3.sierra.bottle.1.tar.gz
http://px4-travis.s3.amazonaws.com/toolchain/bottles/sdformat4-4.2.0_2.sierra.bottle.1.tar.gz
http://px4-travis.s3.amazonaws.com/toolchain/bottles/simbody-3.5.4_1.sierra.bottle.1.tar.gz

### CODE REVIEW

**Comment by scpeters** [comment]
How important is it to support gazebo7 on Sierra? qt4 is not supported on Sierra or hosted in the core homebrew tap, so I added the `qt4-no-webkit` formula in #179 to keep gazebo7 and earlier working on 10.11 and earlier, but I had been thinking of not supporting gazebo7 on Sierra. We will be releasing gazebo8 in a couple weeks, which uses qt5. It will be released on Ubuntu Xenial but not trusty.

So I'd appreciate hearing your thoughts on platform support.

**Comment by LorenzMeier** [comment]
We're currently trying to use Gazebo with real drone customers. If your goal is to have traction with Gazebo in the industry then there is simply no way around supporting the current Mac OS version with your current Gazebo release. A gap of a few weeks is a no-no because they can't work in that time frame (Gazebo 8 does not build on Sierra for me). We are doing this right now with our own tap but would like to avoid maintaining something in parallel.

**Comment by scpeters** [comment]
If gazebo7 support on Sierra is just a stopgap until gazebo8 is released, I think we could support it temporarily, but I'd prefer not to support gazebo7 long-term, since it depends on an unsupported version of qt. Also, I would have been happy to use the `cartr/qt4` formula, which has bottles for sierra, but it includes an old version of webkit by default, which is a security risk.

**Comment by starthal** [comment]
The OGRE bottle is 404'ing and the build is failing too. I think should be updated to the `1.7.4_2` [formula](https://github.com/osrf/homebrew-simulation/pull/184/files#diff-5bd8f3c7a6496f0fba36efe2bad6b6f1).

**Comment by starthal** [comment]
I think Gazebo 7 support is worthwhile since it's an LTS release: EOL January 2021. ROS Kinetic (EOL May 2021) is also tied to Gazebo 7. (I know ROS isn't officially supported on macOS.)

My team is thinking of migrating to Gazebo 8, but we still have plugins that only work with the `ignition-transport2` API. And all else being equal, we'd like to stick with the LTS version.

**Comment by pickledgator** [comment]
Are the bottle paths currently right? They seem to be pointing to the wrong addresses as compared to the links above:

Error: Failed to download resource "ignition-math2"
Download failed: http://px4-travis.s3.amazonaws.com/toolchain/bottles/ignition-math2-2.6.0_1.sierra.bottle.tar.gz

**Comment by traut** [comment]
Gazebo7 install fails with:
```
$ brew install gazebo7
==> Installing gazebo7 from px4/simulation
Error: px4/simulation/gazebo7 contains conflicting version recursive dependencies:
  boost, boost@1.55
View these with `brew deps --tree px4/simulation/gazebo7`.
```

**Comment by serser** [comment]
same error as @traut

**Comment by mhkabir** [comment]
This commit breaks it https://github.com/osrf/homebrew-simulation/pull/198/commits/6b1e8df6b53a9829daf37a752cc7b18bf49cb879

**Comment by Sam1215** [comment]
@traut @serser I had the same error on friday so i replaced boost@1.55 in sdformat4.rb file with boost and it proceeded but i am getting new errors

..
..
dyld: Library not loaded: /usr/local/opt/protobuf/lib/libprotobuf.12.dylib
  Referenced from: /usr/local/bin/gz
  Reason: image not found
..
..
/usr/local/Cellar/gazebo7/7.4.0_3/include/gazebo-7/gazebo/msgs/time.pb.h:17:2: error: This file was generated by an older version of protoc which is
#error This file was generated by an older version of protoc which is
 ^
/usr/local/Cellar/gazebo7/7.4.0_3/include/gazebo-7/gazebo/msgs/time.pb.h:18:2: error: incompatible with your Protocol Buffer headers.  Please
#error incompatible with your Protocol Buffer headers.  Please
 ^
/usr/local/Cellar/gazebo7/7.4.0_3/include/gazebo-7/gazebo/msgs/time.pb.h:19:2: error: regenerate this file with a newer version of protoc.
#error regenerate this file with a newer version of protoc.
 ^
In file included from Wind.pb.cc:5:
In file included from ./Wind.pb.h:33:
/usr/local/Cellar/gazebo7/7.4.0_3/include/gazebo-7/gazebo/msgs/vector3d.pb.h:17:2: error: This file was generated by an older version of protoc which is
#error This file was generated by an older version of protoc which is
 ^
/usr/local/Cellar/gazebo7/7.4.0_3/include/gazebo-7/gazebo/msgs/vector3d.pb.h:18:2: error: incompatible with your Protocol Buffer headers.  Please
#error incompatible with your Protocol Buffer headers.  Please
 ^
/usr/local/Cellar/gazebo7/7.4.0_3/include/gazebo-7/gazebo/msgs/vector3d.pb.h:19:2: error: regenerate this file with a newer version of protoc.
#error regenerate this file with a newer version of protoc.
 ^
6 errors generated.
...
...
...
/usr/local/Cellar/gazebo7/7.4.0_3/include/gazebo-7/gazebo/msgs/quaternion.pb.h:17:2: error: This file was generated by an older version of protoc which is
#error This file was generated by an older version of protoc which is
 ^
/usr/local/Cellar/gazebo7/7.4.0_3/include/gazebo-7/gazebo/msgs/quaternion.pb.h:18:2: error: incompatible with your Protocol Buffer headers.  Please
#error incompatible with your Protocol Buffer headers.  Please
 ^
/usr/local/Cellar/gazebo7/7.4.0_3/include/gazebo-7/gazebo/msgs/quaternion.pb.h:19:2: error: regenerate this file with a newer version of protoc.
#error regenerate this file with a newer version of protoc.
 ^
In file included from SensorImu.pb.cc:5:
In file included from ./SensorImu.pb.h:33:
/usr/local/Cellar/gazebo7/7.4.0_3/include/gazebo-7/gazebo/msgs/vector3d.pb.h:17:2: error: This file was generated by an older version of protoc which is
#error This file was generated by an older version of protoc which is
 ^
/usr/local/Cellar/gazebo7/7.4.0_3/include/gazebo-7/gazebo/msgs/vector3d.pb.h:18:2: error: incompatible with your Protocol Buffer headers.  Please
#error incompatible with your Protocol Buffer headers.  Please
 ^
/usr/local/Cellar/gazebo7/7.4.0_3/include/gazebo-7/gazebo/msgs/vector3d.pb.h:19:2: error: regenerate this file with a newer version of protoc.
#error regenerate this file with a newer version of protoc.
 ^
6 errors generated.
ninja: build stopped: subcommand failed.
ninja: build stopped: subcommand failed.
make: *** [posix_sitl_default] Error 1

**Comment by mhkabir** [comment]
@Sam1215 I have a workaround for that. Just build gazebo from source so that it syncs with your local protobuf version : 

```
brew reinstall --build-from-source gazebo7
```

**Comment by Sam1215** [comment]
@mhkabir Hi Kabir, thanks for the help .. while that helped - i have stumbled onto another error. Can you please take a look
[2/6] Performing configure step for 'sitl_gazebo'
-- install-prefix: /usr
-- Boost version: 1.64.0
-- Found the following Boost libraries:
--   thread
--   signals
--   system
--   filesystem
--   program_options
--   regex
--   iostreams
--   date_time
--   chrono
--   atomic
-- Boost version: 1.64.0
-- Looking for OGRE...
-- Checking for module 'OGRE'
--   Found OGRE, version 1.7.4
-- Found Ogre Cthugha (1.7.4)
-- Found OGRE: optimized;/usr/local/Cellar/ogre/1.7.4_1/lib/libOgreMain.dylib;debug;/usr/local/Cellar/ogre/1.7.4_1/lib/libOgreMain.dylib
-- Looking for OGRE_Paging...
-- Found OGRE_Paging: optimized;/usr/local/Cellar/ogre/1.7.4_1/lib/libOgrePaging.dylib;debug;/usr/local/lib/libOgrePaging.dylib
-- Looking for OGRE_Terrain...
-- Found OGRE_Terrain: optimized;/usr/local/Cellar/ogre/1.7.4_1/lib/libOgreTerrain.dylib;debug;/usr/local/lib/libOgreTerrain.dylib
-- Looking for OGRE_Property...
-- Found OGRE_Property: optimized;/usr/local/Cellar/ogre/1.7.4_1/lib/libOgreProperty.dylib;debug;/usr/local/lib/libOgreProperty.dylib
-- Looking for OGRE_RTShaderSystem...
-- Found OGRE_RTShaderSystem: optimized;/usr/local/Cellar/ogre/1.7.4_1/lib/libOgreRTShaderSystem.dylib;debug;/usr/local/lib/libOgreRTShaderSystem.dylib
-- Boost version: 1.64.0
-- Found the following Boost libraries:
--   system
--   thread
--   timer
--   chrono
--   date_time
--   atomic
-- Building klt_feature_tracker without catkin
-- Building OpticalFlow with OpenCV
-- catkin DISABLED
-- Checking for module 'protobuf'
--   Found protobuf, version 3.3.0
Gazebo version: 7.4
-- Boost version: 1.64.0
-- Found the following Boost libraries:
--   system
--   thread
--   timer
--   chrono
--   date_time
--   atomic
-- Configuring done
CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:

   LiftDragPlugin
   OpticalFlow
   gazebo_geotagged_images_plugin
   gazebo_lidar_plugin
   gazebo_opticalFlow_plugin
   gazebo_sonar_plugin
   mav_msgs
   rotors_gazebo_controller_interface
   rotors_gazebo_gimbal_controller_plugin
   rotors_gazebo_imu_plugin
   rotors_gazebo_mavlink_interface
   rotors_gazebo_motor_model
   rotors_gazebo_multirotor_base_plugin
   rotors_gazebo_wind_plugin

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /Users/Sameer/src/Firmware/build_posix_sitl_default/build_gazebo
[3/6] Performing build step for 'sitl_gazebo'
FAILED: external/Stamp/sitl_gazebo/sitl_gazebo-build 
cd /Users/Sameer/src/Firmware/build_posix_sitl_default/build_gazebo && /usr/local/Cellar/cmake/3.8.1/bin/cmake --build . && /usr/local/Cellar/cmake/3.8.1/bin/cmake -E touch /Users/Sameer/src/Firmware/build_posix_sitl_default/external/Stamp/sitl_gazebo/sitl_gazebo-build
[1/29] Generating /Users/Sameer/src/Firmware/Tools/sitl_gazebo/models/iris/iris.sdf
FAILED: /Users/Sameer/src/Firmware/Tools/sitl_gazebo/models/iris/iris.sdf 
cd /Users/Sameer/src/Firmware/Tools/sitl_gazebo && rm -f /Users/Sameer/src/Firmware/Tools/sitl_gazebo/models/iris/iris.sdf && python /Users/Sameer/src/Firmware/Tools/sitl_gazebo/scripts/xacro.py -o /Users/Sameer/src/Firmware/Tools/sitl_gazebo/models/rotors_description/urdf/iris_base.urdf /Users/Sameer/src/Firmware/Tools/sitl_gazebo/models/rotors_description/urdf/iris_base.xacro enable_mavlink_interface:=true enable_ground_truth:=false enable_wind:=false enable_logging:=false rotors_description_dir:=/Users/Sameer/src/Firmware/Tools/sitl_gazebo/models/rotors_description && gz sdf -p /Users/Sameer/src/Firmware/Tools/sitl_gazebo/models/rotors_description/urdf/iris_base.urdf >> /Users/Sameer/src/Firmware/Tools/sitl_gazebo/models/iris/iris.sdf && rm -f /Users/Sameer/src/Firmware/Tools/sitl_gazebo/models/rotors_description/urdf/iris_base.urdf

dyld: Symbol not found: __ZNK5boost16re_detail_10630031cpp_regex_traits_implementationIcE17transform_primaryEPKcS4_
  Referenced from: /usr/local/opt/sdformat4/lib/libsdformat.4.dylib
  Expected in: /usr/local/opt/boost/lib/libboost_regex-mt.dylib
 in /usr/local/opt/sdformat4/lib/libsdformat.4.dylib
/bin/sh: line 1: 77787 Abort trap: 6           gz sdf -p /Users/Sameer/src/Firmware/Tools/sitl_gazebo/models/rotors_description/urdf/iris_base.urdf >> /Users/Sameer/src/Firmware/Tools/sitl_gazebo/models/iris/iris.sdf
[2/29] Building CXX object CMakeFiles/mav_msgs.dir/SensorImu.pb.cc.o
[3/29] Building CXX object CMakeFiles/mav_msgs.dir/Wind.pb.cc.o
ninja: build stopped: subcommand failed.
ninja: build stopped: subcommand failed.
make: *** [posix_sitl_default] Error 1

**Comment by Sam1215** [comment]
@mhkabir 
i even tried to uninstall sdformat, sdformat3 and sdformat4 
then reinstall sdformat3 - same error
then uninstall sdformat3 and install sdformat4 - same error.

**Comment by julianoes** [comment]
> dyld: Symbol not found: _ZNK5boost16re_detail_10630031cpp_regex_traits_implementationIcE17transform_primaryEPKcS4

For this one, you need to go back to an older boost version. E.g. `boost@1.55`.

**Comment by mhkabir** [comment]
@julianoes can you fix the dependency for boost such that it doesn't throw this error :
```
Error: px4/simulation/gazebo7 contains conflicting version recursive dependencies:
  boost, boost@1.55
```

**Comment by Sam1215** [comment]
@julianoes how do i revert back to old boost version. I uninstalled the latest boost ver and installed boost@1.55 and i got this warning

then while building I get errors like these ..although i see boost@1.55 folder is installed 

 Unable to find the requested Boost libraries.
  Boost version: 0.0.0

**Comment by scpeters** [comment]
At long last, I've merged gazebo7 bottles for sierra in #251. It is now using the `cartr/qt4` tap. There are also gazebo8 bottles for sierra.

**Comment by scpeters** [comment]
I'm not sure you noticed, but we now have sierra bottles for these packages already in this tap. I don't think this pull request is needed anymore.

**Comment by julianoes** [comment]
@mhkabir I've uploaded new bottles for Sierra, it should work again.

**Pull request closed without merging**
