### PR TITLE
Disable bottles that depend on tinyxml2

### PR DESCRIPTION
**Pull request by mjcarroll**
Signed-off-by: Michael Carroll <michael@openrobotics.org>

### CODE REVIEW

**Comment by j-rivero** [comment]
Sorry but I've totally missed the original problem related to tinyxml2 in brew? Do you have a link at hand?

**Comment by mjcarroll** [comment]
homebrew-core bump: https://github.com/Homebrew/homebrew-core/pull/78882

failing job: https://build.osrfoundation.org/job/sdformat11-install_bottle-homebrew-amd64/27/

**Comment by j-rivero** [comment]
We will need to rebuild the bottles by bumping revisions after this PR, I think is good to go, if something is missing we'll find it a long the way.

**Review by j-rivero — APPROVED** [review]

**Comment by scpeters** [comment]
this is a good start but we need to remove bottles for recursive dependencies as well

**Comment by scpeters** [comment]
> this is a good start but we need to remove bottles for recursive dependencies as well

ah, you've done quite a few, let me see if you've gotten them all

**Comment by scpeters** [comment]
I think we can restore the `sdformat9` bottle, since we didn't migrate to tinyxml2 until sdformat10

**Comment by scpeters** [comment]
> I think we can restore the `sdformat9` bottle, since we didn't migrate to tinyxml2 until sdformat10

reverted for sdformat9 in #1491

**Comment by scpeters** [comment]
I've opened #1492 to unbottle the dependents of sdformat10, 11, and 12

we also need to unbottle the dependents of ignition-msgs and our fork of dartsim

**Pull request merged**
