### PR TITLE
ignition-msgs6 6.4.0, ignition-gazebo4 4.6.0

### PR DESCRIPTION
**Pull request by osrfbuild**

### CODE REVIEW

**Comment by scpeters** [comment]
there was a recent protobuf release, so as noted in #1340 we'll need to bump revisions on a few other packages as well, in a similar manner to #1206

and we can bump ignition-physics3 as well since the build in #1346 failed due to the protobuf issue

**Comment by scpeters** [comment]
build bottle

**Comment by scpeters** [comment]
build bottle

**Comment by scpeters** [comment]
this needs to be combined with #1348 due to the API break in https://github.com/ignitionrobotics/ign-msgs/pull/137

**Comment by scpeters** [comment]
rebuilding ignition-physics3 first in #1346

**Comment by scpeters** [comment]
build bottle

**Comment by chapulina** [comment]
build bottle

**Comment by scpeters** [comment]
this build will probably fail; there's something wrong in the cmake tests for ign-gazebo

**Comment by scpeters** [comment]
build bottle

**Pull request merged**
