### PR TITLE
sdformat12 12.0.0~pre1

### PR DESCRIPTION
**Pull request by osrfbuild**

### CODE REVIEW

**Comment by chapulina** [comment]
build bottle

**Comment by scpeters** [comment]
I was waiting for https://github.com/ignition-tooling/release-tools/pull/518 before triggering the bottles, but we can build them with the next prerelease I suppose

**Comment by chapulina** [comment]
Ah sorry about that

**Comment by scpeters** [comment]
> Ah sorry about that

it's fine; I just need a review of https://github.com/ignition-tooling/release-tools/pull/518

**Pull request merged**
