### PR TITLE
sdformat10 10.4.0

### PR DESCRIPTION
**Pull request by osrfbuild**

### CODE REVIEW

**Comment by scpeters** [comment]
build bottle

**Comment by nkoenig** [comment]
@scpeters , is this safe to merge?

**Comment by scpeters** [comment]
it doesn't have a bottle

**Comment by scpeters** [comment]
the catalina machine is not turning on; I'll go poke it today

**Comment by scpeters** [comment]
we can merge it for now with no bottles

**Comment by nkoenig** [comment]
Okay, thanks.

**Comment by scpeters** [comment]
bottle was built in #1419

**Pull request merged**
