### PR TITLE
ignition-math6 6.9.0~pre1

### PR DESCRIPTION
**Pull request by osrfbuild**

### CODE REVIEW

**Comment by chapulina** [comment]
build bottle

**Comment by chapulina** [comment]
I don't understand what went wrong

```
==> FAILED
Error: undefined method `exist?' for #<String:0x00007fb8d5bdfa70>
/usr/local/Homebrew/Library/Homebrew/formula.rb:315:in `specified_path'
/usr/local/Homebrew/Library/Homebrew/tab.rb:169:in `for_formula'
```

**Comment by chapulina** [comment]
build bottle

**Comment by scpeters** [comment]
> I don't understand what went wrong
> 
> ```
> ==> FAILED
> Error: undefined method `exist?' for #<String:0x00007fb8d5bdfa70>
> /usr/local/Homebrew/Library/Homebrew/formula.rb:315:in `specified_path'
> /usr/local/Homebrew/Library/Homebrew/tab.rb:169:in `for_formula'
> ```

this was a bug in brew: https://github.com/Homebrew/brew/issues/12104, quickly fixed in https://github.com/Homebrew/brew/pull/12105

**Pull request merged**
